### ISSUE TITLE
Create protocol to interface w/ remote members of the team re: kanban

### ISSUE THREAD

**Issue by hellyeah** [hackclub/meta#100]

**Comment by zachlatta** [comment]
Hmm, so I think there's a couple ways to approach this.

First and foremost, and regardless of how we decide to accomplish this, I
think it's important that we document how we do standups somewhere so it's
in writing. I know http://ipfs.io/ keeps track of their project/product
management systems in https://github.com/ipfs/pm. We tried a similar thing
with https://github.com/hackedu/pm, but ended up dropping the system they
were using.

One idea is to do our standups in IRC every morning, but I'm worried that
at the speed we're trying to accomplish things (and how much changes day to
day), we'd run into some serious communication breakdowns.

What if we continue to do standups every morning in person, but document
that process in `hackedu/meta` so people outside of the organization know
what's up?

Thoughts?

/cc @jonleung @MaxWofford @gemmabusoni

On Tue, Aug 18, 2015 at 12:37 PM, David Fontenot <notifications@github.com>
wrote:

> Assigned #100 <https://github.com/hackedu/meta/issues/100> to @zachlatta
> <https://github.com/zachlatta>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/100#event-385746733>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, I think that is a good start!

**Comment by MaxWofford** [comment]
@zachlatta I'm down with that.

**Comment by zachlatta** [comment]
Closing this since it seems we've standardized on using Google Hangouts at 9AM every morning.
