### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#117]
Moved from hackedu/finances#5.

From @hellyeah's original description:

- - -

Will need to do extensive research on the options that exist.

We should adopt a Code of Conduct from an organization that deeply understands the issues our community members might face (has a diverse leadership itself).

**Comment by zachlatta** [comment]
@hellyeah so I was taking a look at the Hackathon Hackers code of conduct (https://github.com/HackathonHackers/code-of-conduct) and while it may be a good place to start, it doesn't have a license, which prevents us from using it or parts of it, as-is. I created HackathonHackers/code-of-conduct#8 to track the missing license.

**Comment by hellyeah** [comment]
@zachlatta JB added a license. There are a bunch of options though -- we don't need to restrict ourselves to HH's Code of Conduct. 

I'm pushing for it bc I know that it's going to be actively maintained and updated to contain a lot of specifics that will exist in this community too. 

It might easier to just go with a more established Code of Conduct for now though. Will look into different ones.

**Comment by zachlatta** [comment]
Sounds good! I'll let you take point on this, I trust your judgement.

On Fri, Aug 28, 2015 at 10:16 AM, David Fontenot <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> JB added a license. There are a
> bunch of options though -- we don't need to restrict ourselves to HH's Code
> of Conduct.
>
> I'm pushing for it bc I know that it's going to be actively maintained and
> updated to contain a lot of specifics that will exist in this community
> too.
>
> It might easier to just go with a more established Code of Conduct for now
> though. Will look into different ones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/117#issuecomment-135836558>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by hellyeah** [comment]
Might be good to pass this by club leaders.

**Comment by hellyeah** [comment]
Set aside time to do this on Thursday. May pair with @zachlatta while he does https://github.com/hackedu/hack-camp/issues/529 if he hasn't completed the task by then. Will also ping club leaders to check it out and submit comments/PRs.

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by jonleung** [comment]
As discussed with @zachlatta in person earlier today (Wed Dec-16) I've taken this task off of him and assigning myself!

**Comment by jonleung** [comment]
Additional work that needs to be done to complete this task:

**Facebook**
- [ ] Linking to the Code of Conduct in the description of [the Facebook Group](https://www.facebook.com/groups/1501083703514499/)
- [ ] Post in [Facebook Group](https://www.facebook.com/groups/1501083703514499) announcing that we are adopting this Code of Conduct and ask for feedback and pull requests

**Slack**
- [ ] Linking to the Code of Conduct in the Slack
- [ ] Post in `#announcements` on Slack saying we are adopting this code of conduct and ask for feedback and pull requests

@hackclub/staff, are there any other places that we should post / announce this?

**Comment by jonleung** [comment]
@zachlatta can you setup `conduct@hackclub.io` so that it forwards to Jonathan, Harrison, and Zach?

**Comment by zachlatta** [comment]
Done!

**Comment by zachlatta** [comment]
I've also linked to the code of conduct in the Facebook group description in #301. I'll leave it to you to check that box in your previous comment.

**Comment by MaxWofford** [comment]
@zachlatta @jonleung What if the `conduct@hackclub.io` email forwarded to `team@hackclub.io`?

**Comment by jonleung** [comment]
@maxwofford, the reason why we decided not to forward 'conduct@hackclub.io' to 'team@hackclub.io' is because as the team grows and changes, we don't want the people who are responsible for handling the conduct to automatically change.

**Comment by jart** [comment]
Code of conduct? I can't believe people take those things seriously. It's just childish rubbish promoted by people with a political agenda. Keep that nonsense out of engineering.

We don't need a code of conduct. FOSS is the first culture, in the history of mankind, that's truly international, post-monetary, and discrimination on the basis of race, sex, age, etc. is impossible. Welcome to the Internet. It unites the human race. And hackers invented it.

**Comment by zachlatta** [comment]
We created our code of conduct with three goals in mind: (1) to specify a
baseline standard of behavior, (2) to provide a mechanism for resolving
conflicts in the community when they arise, and (3) to make our community
welcoming to people from different backgrounds.

The third is the only political goal and even then, I think the actual
contents of the code of conduct don't get very political (they're mostly
about making behavior that's "common sense" explicit). It's also important
to keep in mind that Hack Club is primarily composed of in-person chapters
where discrimination does happen and biases are prevalent.

On Tue, Jan 5, 2016 at 5:35 PM, Justine Alexandra Roberts Tunney <
notifications@github.com> wrote:

> Code of conduct? I can't believe people take those things seriously. It's
> just childish rubbish promoted by people with a political agenda. Keep that
> nonsense out of engineering.
>
> We don't need a code of conduct. FOSS is the first culture, in the history
> of mankind, that's truly international, post-monetary, and discrimination
> on the basis of race, sex, age, etc. is impossible. Welcome to the
> Internet. It unites the human race. And hackers invented it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/117#issuecomment-169191096>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jart** [comment]
Are you implying Hack Club wasn't welcoming of people from different backgrounds before? Oh my goodness.

**Comment by zachlatta** [comment]
No, I'm saying that the code of conduct is valuable because it makes inappropriate behaviors explicit.

This issues should also be closed. We've already added our code of conduct over at https://github.com/hackclub/hackclub/blob/master/CONDUCT.md.

**Comment by samhatchett** [comment]
this user is spamming many projects - i suggest anyone following this issue file an abuse report:
https://github.com/jart?tab=activity
https://github.com/contact?report=jart

**Comment by zachlatta** [comment]
Ah, thank you for the heads up!
