### ISSUE TITLE
slack.hackedu.us redirect to hackedu.slack.com

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#217]
[This is another alternative](https://www.namecheap.com/domains/registration/results.aspx?domain=slackedu.us)

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by MaxWofford** [comment]
This is addressed by https://github.com/hackclub/slackin/pull/1. If you want to implement it now, feel free to reopen the PR. Otherwise you may want to wait for upstream to be fixed

**Comment by zachlatta** [comment]
Thanks Max! :heart:

On Thu, Jan 7, 2016 at 9:23 AM, Max Wofford <notifications@github.com>
wrote:

> Closed #217 <https://github.com/hackclub/meta/issues/217>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/217#event-508500411>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
