### ISSUE TITLE
Move DNS to a GitHub repo

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#222]

**Comment by zachlatta** [comment]
Yeah, I'm in. Let's do this.

**Comment by MaxWofford** [comment]
![](http://quickme.me/justdoit.gif)

**Comment by jonleung** [comment]
@zachlatta should we move this issue to Backlog because you're assigned to it as per our agreement that any assigned tasks should be in backlog?

**Comment by MaxWofford** [comment]
@zachlatta idk if it helps, but I just got my subdomains set up in a repo here https://github.com/maxwofford/subdomains.

**Comment by zachlatta** [comment]
Is that just an nginx config for redirects or also your DNS setup? Looks
like the former to me.

On Sun, Jan 10, 2016 at 5:43 AM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> idk if it helps, but I just got
> my subdomains set up in a repo here
> https://github.com/maxwofford/subdomains.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/222#issuecomment-170345438>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
@zachlatta Just nginx config, but we're still at a small enough rate of traffic this could work.

**Comment by zachlatta** [comment]
This issue is specifically for our DNS config, which nginx won't be able to
handle. It'd be nice to also have our nginx config in a GitHub repo as well
though.

On Sun, Jan 10, 2016 at 7:34 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Just nginx config, but we're
> still at a small enough rate of traffic this could work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/222#issuecomment-170424919>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Going to go ahead and close this because it's not a priority.
