### ISSUE TITLE
The #hackedu channel in Slack is confusing for club leaders

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#234]
Numerous club leaders have asked me what the `#hackedu` channels is in Slack. I think it would be beneficial to:

1. Rename the channel to something clearer like `#irc-bridge` or something
2. Write a clear description of what the channel is

@zachlatta, would you be interested in taking this task?

/cc @zachlatta @hellyeah @MaxWofford @amysorto

**Comment by MaxWofford** [comment]
Can we remove the general channel, or connect the irc-bridge to the general channel?

**Comment by paked** [comment]
@MaxWofford Moving the IRC bridge to the general channel would work. My only concern is that people introducing themselves would be noticed less.

**Comment by jonleung** [comment]
I think moving the irc-bridge to the general channel would be cool to try. I think it will will make irc#hackedu less 2nd class.

Thoughts @hellyeah @zachlatta?

**Comment by hellyeah** [comment]
We have to make a design decision whether the IRC or slack is a first-class citizen right?

Additionally, do we want all the bots posting?

**Comment by paked** [comment]
@hellyeah which bots do you mean?

**Comment by MaxWofford** [comment]
We don't have this channel about it
