### ISSUE TITLE
Ask Soylent for in kind donation

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#236]
@hellyeah, [here is a template](https://gist.github.com/jonleung/f941aae9423c1f573632) that I used in the past (with Soylent filled in).

**Comment by hellyeah** [comment]
I emailed Soylent about hackingEDU earlier this week.

**Comment by hellyeah** [comment]
Going to email them again on Monday about hackEDU specifically.

**Comment by hellyeah** [comment]
Talking to them at 1pm today.

**Comment by jonleung** [comment]
Closing this because it doesn't seem like it is high leverage to do in the immediate future.
