### ISSUE TITLE
Onboard all hackEDU leaders onto Slack

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#237]
_From @jonleung on October 21, 2015 1:7_

**Especially**

- [ ] Cohort 2 Leaders
  - [ ] Add them to the `#cohort-2`
- [ ] Make sure everyone has accepted their slack invite (see https://hackedu.slack.com/admin/invites)
- [ ] Anyone else you think we should add

**Mobile App**
- [ ] Make sure everyone has
  - [ ] Downloaded the mobile app
  - [ ] Has enabled push notifications

@hellyeah @zachlatta, what are your thoughts on adding this task for this week?

_Copied from original issue: hackedu/hackedu#376_

**Comment by zachlatta** [comment]
Do we want to add cohort 2 leaders now @hellyeah? I know we also have hackedu/hackedu#313 created.

**Comment by hellyeah** [comment]
Yes. Adding cohort 2 leaders today.

**Comment by MaxWofford** [comment]
It seems that everyone on slack is fairly acquainted with it
