### ISSUE TITLE
Schedule Fun Team Activity

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#261]
SInce we are biasing to schedule all meetings / one-on-ones and possibly calls on Wednesday, what if we moved our team activity to wednesday night?

I propose evening because

1. It's after work so we would feel more relaxed
2. More "fun stuff" is open then

I propose 6:30pm because if people want to do things at night, this still gives people ample room to do that.

I think it would be fun to change this 6:30pm activity up from week to week but what if for this week we kept it simple and just did dinner somewhere?

/cc @hellyeah @MaxWofford @zachlatta

**Comment by MaxWofford** [comment]
Closing this because the the day passed.

**Comment by MaxWofford** [comment]
That being said, @jonleung, I'm down for a team activity next wednesday if anyone wants to pick up organizing it.

/cc @zachlatta
