### ISSUE TITLE
Schedule 4 paired calls with 8 club leaders

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#263]
@jonleung made tentative pairs here: https://docs.google.com/spreadsheets/d/1Mb-8WBjiZUOYgWqNJxaigCWZvZqnIHZ2ZhokVNCbJ4g/edit#gid=1880595778

- [ ] Jeremy <> Jiahao (Tuesday)
- [ ] Amy <> Jevin 
- [ ] Tejas <> Samuel

**Comment by zachlatta** [comment]
_From @hellyeah on October 29, 2015 20:42_

Form for post-pairing call

**Comment by zachlatta** [comment]
_From @hellyeah on November 2, 2015 20:29_

We need to effectively track which leaders we've paired so we don't pair them too often.

**Comment by hellyeah** [comment]
Did not end up completing this objective. Doing it this week.

**Comment by zachlatta** [comment]
Closing for the time being. @jonleung, are we still going to do pairing calls?
