### ISSUE TITLE
I asked if Sam's club wanted to join Labs, they said yes!

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#282]
@zachlatta suggested a while back that it would be great to have @saescapa join labs. I agreed and I asked @saescapa if he was interested. He just got back to me saying that he was interested.

Next, I think we

1) Add @saescapa to the #Labs on Slack
2) Ask @saescapa to make an introduction
2) Add @saescapa to the Spreadsheet

Anything else that we need to do?

/cc @zachlatta @MaxWofford @hellyeah

**Comment by MaxWofford** [comment]
We might want to rephrase the task.

**Comment by zachlatta** [comment]
Err, I hate to have this discussion in public, but did we as a team agree to do this?

**Comment by MaxWofford** [comment]
@jonleung Replaced by https://github.com/hackclub/meta/issues/317
