### ISSUE TITLE
Ping clubs wed and before who did not submit curriculum / attendance

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#294]
\cc @MaxWofford

**Comment by jonleung** [comment]
@MaxWofford, did you get a confirmation from any leaders from any of these schools who said they would be down to do use the hackEDU Labs Curriculum & Attendance Spreadsheet?

- Cherry Hill High School East
- Elizabeth High School
- San Mateo High School

This will change the way I will reach out to them. Thanks!

**Comment by MaxWofford** [comment]
@jonleung Nothing yet.

**Comment by jonleung** [comment]
Closed in favor of #330
