### ISSUE TITLE
Club Leader Pairing

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#297]
_From @hellyeah on September 28, 2015 16:40_

_Copied from original issue: hackedu/hackedu#272_

**Comment by zachlatta** [comment]
As discussed, @gemmabusoni will be reaching out to @Bogidon to pair on `planning.md` and `recap.md`.

**Comment by zachlatta** [comment]
_From @gemmabusoni on September 30, 2015 5:35_

@jonleung mentioned that Bogdan is rather swamped this week. Haven't received feedback as to who I should potentially be partnering with instead.

**Comment by zachlatta** [comment]
_From @hellyeah on October 7, 2015 16:4_

Gemma and Jeremy (Lowell)

**Comment by zachlatta** [comment]
_From @gemmabusoni on October 9, 2015 16:15_

Call with Jeremy scheduled for 3pm Saturday. I'll be taking it from CalHacks, in case anyone else wanted to be involved.

**Comment by zachlatta** [comment]
_From @hellyeah on October 21, 2015 16:8_

@gemmabusoni how's this going?

**Comment by zachlatta** [comment]
_From @gemmabusoni on October 25, 2015 6:16_

@hellyeah Call was done on said day; he submitted to GitHub as well.

**Comment by zachlatta** [comment]
_From @MaxWofford on October 25, 2015 12:54_

@gemmabusoni Would you please link that here?

**Comment by jonleung** [comment]
Closing this because it no longer seems relevant.
