### ISSUE TITLE
Encourage club leaders to add their club members to the public Facebook Group

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#298]
_From @hellyeah on August 27, 2015 22:15_

We should give them copy that emphasizes our values from before their members even enter the Facebook Group.

This blocks on #109 

_Copied from original issue: hackedu/hackedu#110_

**Comment by zachlatta** [comment]
@jonleung perhaps this may be a good opportunity to start clarifying our
organizational values as well?

On Thu, Aug 27, 2015 at 3:15 PM, David Fontenot <notifications@github.com>
wrote:

> We should give them copy that emphasizes our values from before their
> members even enter the Facebook Group.
>
> This is
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/110>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
_From @jonleung on August 28, 2015 16:41_

@zachlatta, I agree. Any specific actionable steps that you think we can take on this @zachlatta?

**Comment by zachlatta** [comment]
Should we still plan on doing this?

**Comment by zachlatta** [comment]
_From @paked on October 26, 2015 19:54_

Do we even have a public facebook group?

**Comment by zachlatta** [comment]
_From @jonleung on October 28, 2015 21:26_

@paked we want to create one.

**Comment by jonleung** [comment]
Updated the title to reflect that creating a public facebook page is required for this task to happen.

**Comment by jonleung** [comment]
Changing the title back because we actually tracking the creation of this FB goup in #302

**Comment by zachlatta** [comment]
Closing because #109 was closed.
