### ISSUE TITLE
Add all Labs Leaders to Medium publication

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#299]
_From @hellyeah on September 17, 2015 17:9_

_Copied from original issue: hackedu/hackedu#220_

**Comment by zachlatta** [comment]
_From @hellyeah on September 17, 2015 20:22_

Added a Medium column to http://clubs.hackedu.us

**Comment by zachlatta** [comment]
Can you make sure to include an owner and expiration date, per the README
@hellyeah?

On Thu, Sep 17, 2015 at 1:22 PM, David Fontenot <notifications@github.com>
wrote:

> Added a Medium column to http://clubs.hackedu.us
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/220#issuecomment-141216907>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta do you think we should still do this?

**Comment by zachlatta** [comment]
We're no longer doing Labs, closing.
