### ISSUE TITLE
Business cards

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#30]
EDIT 08-20-15: Actionable task:

Take [these files](http://cl.ly/1b2r0I0T1J2U) and make the following change:

> It'd be great if the name could be moved lower down, perhaps right above
> the phone number? It'd also be great if you could include a position for
> our job title.

---------------------------------------------------------------------------------

Create business cards for:

* @andreadeng
* @jonleung
* @benzweig 
* @gemmabusoni 
* @MaxWofford 
* @zachlatta

**Comment by jonleung** [comment]
@benzweig Hey! Good seeing ya today! Any updates as for the timeline for this? If you don't have time now, no worries! Thanks!

**Comment by zachlatta** [comment]
@benzweig would it be cool if @andreadeng took over this issue?

**Comment by benzweig** [comment]
hey, i had assumed she had. i’ll send what i got if she wants

**Comment by zachlatta** [comment]
Sounds good – thanks!

**Comment by jonleung** [comment]
Closing because it seems like this will not get done and is not that high leverage.

**Comment by MaxWofford** [comment]
I'm ok with this. We can reopen when business cards become a blocking issue.
![](http://images.sodahead.com/polls/004355063/4719544930_i_m_ok_with_this__n1296497202304__super_answer_2_xlarge.png)

**Comment by zachlatta** [comment]
I'd actually move towards raising the priority of this and trying to push
for it getting done. I'll be going to a few networking events in the fall
and it'll be important for me to have cards.

Thoughts?

Sidenote: @MaxWofford, where do you find all of these amazing images?

On Tue, Aug 18, 2015 at 4:48 PM, Max Wofford <notifications@github.com>
wrote:

> I'm ok with this. We can reopen when business cards become a blocking
> issue.
>
> <https://camo.githubusercontent.com/fec6cc1c5fbf8aa7f99f3b22753ea5ebc2209e73/687474703a2f2f696d616765732e736f6461686561642e636f6d2f706f6c6c732f3030343335353036332f343731393534343933305f695f6d5f6f6b5f776974685f746869735f5f6e313239363439373230323330345f5f73757065725f616e737765725f325f786c617267652e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/30#issuecomment-132392659>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, who would you recommend taking lead on this?

Also, instead of making nice cards, we can use the crappy ones that I made:

- [Front](http://cl.ly/1U3Q3U3L2B1E)
- [Back](http://cl.ly/3e1F0r0D1d2X)

_Note that if @hackedu/core thinks the back is weird, we can just use the front_

Thoughts?

**Comment by zachlatta** [comment]
I think if we slightly modified the front, it could suffice. What if we did something with the back about learning or hacking?

Perhaps starting with "the last thing I built was X"?

**Comment by zachlatta** [comment]
Going to reopen this issue for the sake of discussion.

**Comment by jonleung** [comment]
1. @zachlatta, let me know what you want fixed on the front.
2. Thoughts on ordering 100 cards for each person with just the front and no back for now? We can think about how to make an awesome back for the next iteration.

**Comment by zachlatta** [comment]
Couple things:

It'd be great if the name could be moved lower down, perhaps right above
the phone number? It'd also be great if you could include a position for
our job title.

If we buy nice cards from Moo, it looks like they'd come out to around 50
cents each. Would it be alright if we just ordered them on an ad-hoc basis
instead of for everyone all at once? At least until we have a logo
finalized.

On Thu, Aug 20, 2015 at 2:41 PM, Jonathan Leung <notifications@github.com>
wrote:

>
>    1. @zachlatta <https://github.com/zachlatta>, let me know what you
>    want fixed on the front.
>    2. Thoughts on ordering 100 cards for each person with just the front
>    and no back for now? We can think about how to make an awesome back for the
>    next iteration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/30#issuecomment-133186665>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
> It'd be great if the name could be moved lower down, perhaps right above
> the phone number? It'd also be great if you could include a position for
> our job title.

Cool. I've edited the description at the top of this issue to reflect this.

> If we buy nice cards from Moo, it looks like they'd come out to around 50
> cents each. Would it be alright if we just ordered them on an ad-hoc basis
> instead of for everyone all at once? At least until we have a logo
> finalized.

Sounds good.

**Comment by MaxWofford** [comment]
Closing this discussion. Another issue should be opened if we want to get business cards.
