### ISSUE TITLE
Revamp the description on hackEDU Leaders Facebook Group

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#301]
_From @hellyeah on August 29, 2015 0:14_

https://www.facebook.com/groups/1501083703514499

_Copied from original issue: hackedu/hackedu#118_

**Comment by zachlatta** [comment]
Thoughts on the following?

    The community of people leading Hack Clubs around the world.

    Code of conduct: https://example.com

    New members comment on this post: https://facebook.com/examplepost

**Comment by MaxWofford** [comment]
@zachlatta :+1:

**Comment by zachlatta** [comment]
Updated!

**Comment by zachlatta** [comment]
I'm thinking it may be worth our time to add a shortlink to our code of conduct (ex. https://conduct.hackclub.io)

**Comment by paked** [comment]
@zachlatta sgtm
