### ISSUE TITLE
Create new public Facebook Group for all hackEDU leaders and those clubs' members

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#302]
_From @hellyeah on August 27, 2015 22:13_

Leaders should be heavily encouraged to add their members to this group once we get it going. Will be cool for them to be part of a broader community.

Think HS Hackers but we emphasize core values, specifically inclusion and mentorship, from the start. 

We should adopt a Code of Conduct before we launch this group. Here's the one we're developing openly for HH: http://hh.gd/conduct

_Copied from original issue: hackedu/hackedu#109_

**Comment by zachlatta** [comment]
_From @jonleung on August 28, 2015 16:16_

Dependent on https://github.com/hackedu/meta/issues/117, which tracks the code of conduct.

**Comment by zachlatta** [comment]
Created https://www.facebook.com/groups/1647912265454317/ and added @jonleung, @MaxWofford, and @hellyeah as admins.

Still need to adopt a code of conduct before we start adding members. @hellyeah can you take point on that?

**Comment by zachlatta** [comment]
_From @hellyeah on August 31, 2015 18:35_

Blocking on hackedu/meta#117

**Comment by zachlatta** [comment]
Moved to the ideas column because we've decided to prioritize getting the main leaders Facebook group going before starting this group as well.

**Comment by zachlatta** [comment]
Thoughts on continuing this @MaxWofford, @jkwok91, @remixz? I'm thinking about closing it for now.

**Comment by remixz** [comment]
:+1: to closing the leaders group... we should keep all of our communication in one place. Slack seems to be the best choice for now.

**Comment by zachlatta** [comment]
Gonna close. Happy to reopen if anyone has any objections.
