### ISSUE TITLE
Plan and Schedule future curriculum calls

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#303]
_From @jonleung on November 3, 2015 6:46_

I've dropped the ball on making this happen. Let's set this up again.

Before each call, we should have a clear objective of what we want to get out of the call.
More concretely, each call should also have an agenda.

\cc @Bogidon @paked @JevinSidhu

_Copied from original issue: hackedu/hackedu#456_

**Comment by zachlatta** [comment]
Can you clarify what you mean by a "curriculum call"?

**Comment by zachlatta** [comment]
_From @jonleung on November 3, 2015 6:48_

Calls where we talk about curriculum in general, how to collaborate on it, what we might change, what's working and not working, etc. For context, we've been having these almost every week for the past several weeks until recently.

**Comment by zachlatta** [comment]
Could these be done during the pairing calls?

**Comment by zachlatta** [comment]
_From @paked on November 3, 2015 6:52_

@zachlatta It has worked really well having a group of people come together to talk about *one* specific topic.

**Comment by zachlatta** [comment]
Ah, gotcha. Proceed as planned then :-).

**Comment by zachlatta** [comment]
_From @paked on November 3, 2015 6:53_

I'd love to be kept in the loop about this. I can do Fridays and Saturdays 3pm PT onwards (Thanks Australia!), although understand that that makes it difficult for everyone.

**Comment by zachlatta** [comment]
_From @jonleung on November 3, 2015 7:37_

Fridays work best for me right now.

**Comment by zachlatta** [comment]
_From @jonleung on November 3, 2015 7:38_

@JevinSidhu  Friday doesn't work for you though?

**Comment by zachlatta** [comment]
_From @JevinSidhu on November 3, 2015 15:27_

@jonleung They are harder for me, but I can make something work! 

@paked Saturdays from 3pm PT works for me :)

**Comment by jonleung** [comment]
I'm closing this for right now because it seems that the discussion that's happening in the Slack `#curriculum` channel is decently satisfactory. Let me know if anyone would like to continue these calls!
