### ISSUE TITLE
Get every cohort 2 labs leader to message Slack

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#305]
_From @hellyeah on October 26, 2015 17:40_

Last week, I asked cohort 2 labs leaders to shift their chat to Slack: #313 

This week, I want them all to give their cohort chat a status update.

_Copied from original issue: hackedu/hackedu#419_

**Comment by zachlatta** [comment]
Status on this?

**Comment by paked** [comment]
Is this still relevant @zachlatta?

**Comment by zachlatta** [comment]
Nope, let's go ahead and close it for the time being.
