### ISSUE TITLE
The Hack Strikes Back logo

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#307]
vectorize 
![the_hack_strikes_back](https://cloud.githubusercontent.com/assets/5891442/11203701/5e938dca-8cab-11e5-9312-97dea9cd4fe8.png)

**Comment by zachlatta** [comment]
This is amazing.

Can you make "hack" capitalized too?

**Comment by MaxWofford** [comment]
This logo has been added to the hackEDU dropbox

**Comment by zachlatta** [comment]
Can you submit a pull request for it?
