### ISSUE TITLE
Ping club leaders on day of their meetings about attendance and curriculum spreadsheet

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#315]

**Comment by gemmabusoni** [comment]
@MaxWofford Added USC Hybrid High info to the spreadsheet

**Comment by MaxWofford** [comment]
@gemmabusoni 

![](http://quickme.me/loveit.gif)

**Comment by zachlatta** [comment]
Closing this issue in favor of #350, which I've created for this week.
