### ISSUE TITLE
Onboard 2 additional clubs

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#317]
I will take on onboarding 2 additional club as discussed in our weekly planning call tuesday.

Jonathan's Personal note:

I'm not sure they're collecting attendance but I can 
- try to get their curriculum of they choose
- ask them if they would be down to collect attendance

**Comment by zachlatta** [comment]
To hackEDU or to Labs?

**Comment by jonleung** [comment]
@zachlatta Labs

**Comment by MaxWofford** [comment]
@jonleung Any updates on this?

**Comment by jonleung** [comment]
@zachlatta can I actually get your help on completing this. I thought I would be able to do it earlier today but now that I've learned that my body has not recovered, I don't think I'm likely to be able to successfully complete this. If you could do me a favor and take this, that would be amazing. Thanks!

**Comment by jonleung** [comment]
@zachlatta said that he was able to do me a favor and take this task from me on Slack. Thanks @zachlatta! Assigning you now!

**Comment by zachlatta** [comment]
We decided offline that @jonleung would actually take point on this.

**Comment by jonleung** [comment]
I called Sam about this. The task is complete.
