### ISSUE TITLE
Rename hubot to prophet orhpeus

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#321]
And change its icon to a robot dino.

**Comment by paked** [comment]
Can you have multi word usernames? Perhaps it'd be better just to call it `orpheus`

**Comment by MaxWofford** [comment]
Paked :+1:

**Comment by zachlatta** [comment]
@MaxWofford hope it's cool if I assign you :-)

**Comment by MaxWofford** [comment]
This is a duplicate issue of https://github.com/hackclub/meta/issues/342
