### ISSUE TITLE
Remove all instances of hackEDU from GitHub repository descriptions

### ISSUE THREAD

**Issue by paked** [hackclub/meta#325]

**Comment by zachlatta** [comment]
Do you see any offending repos?

**Comment by paked** [comment]
Sloth Gifs

**Comment by paked** [comment]
The frontend legacy

**Comment by paked** [comment]
I'll compile a list when I get home. Currently on mobile :)

**Comment by paked** [comment]
@zachlatta OK. These are the current offenders.

* [ ] https://github.com/hackclub/sloth-gifs
* [ ] https://github.com/hackclub/website
* [ ] https://github.com/hackclub/hack-camp
* [ ] https://github.com/hackclub/hackedu-legacy (possibly should be kept for legacy reasons)
* [ ] https://github.com/hackclub/frontend-legacy (possibly should be kept for legacy reasons)

**Comment by jonleung** [comment]
We can probably leave hack camp alone because it is a legacy project.

**Comment by zachlatta** [comment]
Alright, `sloth-gifs` and `website` are both fixed. Let's keep references to hackEDU in `hack-camp`, `hackedu-legacy`, and `frontend-legacy` for archival purposes.
