### ISSUE TITLE
Standardize system on how to collect attendance

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#333]
_From @jonleung on November 26, 2015 6:58_

@zachlatta and @MaxWofford, I know that last week you were fairly successful at collecting attendance data. What specific things do we should do going forward to continue to be successful at collecting attendance data?

_Copied from original issue: hackclub/hackclub#517_

**Comment by zachlatta** [comment]
_From @MaxWofford on November 26, 2015 9:43_

@jonleung The more club leaders using the auto sms-service, the less we will have to ping on slack. Make sure to remind people it exists.

**Comment by MaxWofford** [comment]
Closing this for now due to inactivity and no clear end-goal.
