### ISSUE TITLE
Link curriculum and attendance spreadsheet via hackclub.io URL

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#334]
_From @jonleung on November 26, 2015 6:55_

_Note that I'm deliberately not linking the attendance and curriculum spreadsheet here so that they are not publicly accessible._

What if we used `attendance.hackclub.io` to link to the curriculum and attendance spreadsheet?

\cc @zachlatta @MaxWofford

_Copied from original issue: hackclub/hackclub#516_

**Comment by zachlatta** [comment]
_From @MaxWofford on November 26, 2015 9:41_

> Note that I'm deliberately not linking the attendance and curriculum spreadsheet here so that they are not publicly accessible.

> `attendance.hackclub.io`

@jonleung Doesn't including this link defeat the purpose of hiding the spreadsheet?

**Comment by jonleung** [comment]
@zachlatta agreed, closing this issue.
