### ISSUE TITLE
Collect attendance and curriculum @zachlatta

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#335]
_From @MaxWofford on November 24, 2015 22:53_

- [x] Hybrid
- [x] Glenaeon
- [x] Armijo

_Copied from original issue: hackclub/hackclub#515_

**Comment by zachlatta** [comment]
Just messaged everyone about setting up a weekly call for this.

**Comment by zachlatta** [comment]
Okay, weekly calls set up with everyone!

**Comment by zachlatta** [comment]
And we're done!

**Comment by MaxWofford** [comment]
:+1:
