### ISSUE TITLE
Hack Club SEO

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#336]
Thanks to AlexB for reminding us that our SEO is not very good:

https://s3.amazonaws.com/f.cl.ly/items/0K2N0Z0h3C0U0j0U3830/Image%202015-11-30%20at%2012.20.50%20PM.png?v=b7663941

**Comment by zachlatta** [comment]
I've added hackclub.io to Google's webmaster tools and have requested it to be re-indexed. Hopefully that'll help.
