### ISSUE TITLE
Create new Hack Club logo

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#338]
Make an acceptable logo for our rename

![export](https://cloud.githubusercontent.com/assets/5891442/11493039/444853b6-97a9-11e5-8b9c-bc445309ac31.png)
![export](https://cloud.githubusercontent.com/assets/5891442/11493044/5401ce86-97a9-11e5-934c-dfc31f7278a3.png)

**Comment by zachlatta** [comment]
Current status update on this. We're waiting on me to talk to 99designs and @MaxWofford will send more of his current logos to the #meta channel on Slack.

**Comment by MaxWofford** [comment]
![screenshot from 2015-12-01 21 08 49](https://cloud.githubusercontent.com/assets/5891442/11640234/65a4bfee-9ce6-11e5-91a2-52f4adec7a16.png)

**Comment by MaxWofford** [comment]
![export](https://cloud.githubusercontent.com/assets/5891442/11640961/633ff760-9cea-11e5-80f4-e984c3c15c56.png)

**Comment by zachlatta** [comment]
Last one is my favorite. What would it look like on a white background (in the case that we're on the sponsors list of a hackathon or something similar).

**Comment by MaxWofford** [comment]
![export](https://cloud.githubusercontent.com/assets/5891442/11644201/f6be1f12-9cfe-11e5-9690-bc81041ff0e2.png)

**Comment by MaxWofford** [comment]
@hackclub/hackclub Thoughts on the [last](https://github.com/hackclub/meta/issues/338#issuecomment-162678015) [two](https://github.com/hackclub/meta/issues/338#issuecomment-162714052)?

**Comment by ssun098** [comment]
I like the last one!

**Comment by MaxWofford** [comment]
@hackclub/staff Thoughts?

**Comment by MaxWofford** [comment]
Revised version of the last one: 

![export](https://cloud.githubusercontent.com/assets/5891442/11678000/c83bd3f0-9df8-11e5-88c1-472b793829ec.png)

**Comment by MaxWofford** [comment]
Revised again:

![export](https://cloud.githubusercontent.com/assets/5891442/11678068/44a0494e-9df9-11e5-8a2b-fc0c5a4da38d.png)

**Comment by MaxWofford** [comment]
![export](https://cloud.githubusercontent.com/assets/5891442/11678149/e02537ee-9df9-11e5-8451-e7db8d1d9b47.png)

**Comment by MaxWofford** [comment]
@hackclub/staff feel free to close this if we're done here

**Comment by jonleung** [comment]
The gradient fade to blur looks a bit off to me, I think it could be done well but I think we should just leave it off for now. I think it's fine just to move forward with the plain logo (just the font color and the background color with the new font)

**Comment by MaxWofford** [comment]
@jonleung Just checking, but do you have flux enabled? (it was on @zachlatta's screen and it looked funny)

**Comment by jonleung** [comment]
@MaxWofford my flux was on. I'm down for whatever. I'll defer to your judgement!

**Comment by zachlatta** [comment]
I love them.

Can you submit a PR with
https://github.com/hackclub/meta/issues/338#issuecomment-162669248 and
https://github.com/hackclub/meta/issues/338#issuecomment-163121916? They're
my two favorites.

**Comment by MaxWofford** [comment]
@zachlatta Did you mean to link to those? Those have different `H`s
