### ISSUE TITLE
Fix Hubot's contribution count

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#341]

**Comment by zachlatta** [comment]
I'm honestly not quite sure what to do about this. GitHub is giving us this error when we make requests to calculate the contribution count for the week:

```
{ [Error: {"message":"In order to keep the API fast for everyone, pagination is limited for this resource. Check the 
rel=last link relation in the Link response header to see how far back you can traverse.","documentation_url":"https:
//developer.github.com/v3/#pagination"}]
  status: 422,
  json:
   { message: 'In order to keep the API fast for everyone, pagination is limited for this resource. Check the rel=las
t link relation in the Link response header to see how far back you can traverse.',
     documentation_url: 'https://developer.github.com/v3/#pagination' } }
```

For the time being I'm going to remove this from my queue while we figure out a better solution (or rewrite it in a way that doesn't query the GitHub event stream).

**Comment by MaxWofford** [comment]
Going to close this for the time being; it looks like GitHub's API really doesn't want us to do this anymore.
