### ISSUE TITLE
Look into getting the other Hack Club domains

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#347]
hackclub.com/hackclub.org/hack.club

**Comment by zachlatta** [comment]
I ended up buying hackclub.com. I think that'll be good enough for the time being.

Going to go ahead and close.

**Comment by MaxWofford** [comment]
Woooo!

(right textbox this time)

**Comment by paked** [comment]
yayyayyayayayayayay

**Comment by zachlatta** [comment]
:tada: :tada: :tada:
