### ISSUE TITLE
Deploy slack-stats-collector

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#348]
From https://github.com/hackclub/slack-stats-collector

**Comment by zachlatta** [comment]
And it's done! https://slack-stats-collector.hackclub.io

**Comment by MaxWofford** [comment]
> https://slack-stats-collector.hackclub.io

@zachlatta This page doesn't load for me

**Comment by zachlatta** [comment]
Ouch, it looks like my deployment is _super broken_.

**Comment by zachlatta** [comment]
And it's done! There was some super janky stuff going on with one of the native dependencies. Thanks nodegit...
