### ISSUE TITLE
Collect curriculum and attendance from last week and this week

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#350]
- @zachlatta
  - [x] Armijo High School
  - [x] Glenaeon Rudolf Steiner School
  - [x] ~~USC Hybrid School~~ _Meeting cancelled due to UC college app deadline extensions_
- @MaxWofford
  - [x] Project Cipher
  - [x] ~~Ravenwood High School~~ _Meets every other week._
  - [x] San Leandro High School
  - [x] South Brunswick High School
- @jonleung
  - [ ] Elizabeth High School
  - [ ] San Mateo High School
  - [ ] Cherry Hill High School East
  - [ ] Lowell High School

**Comment by jonleung** [comment]
As discussed during standups on Thu Dec-17, we decided to close this issue because we want to prioritize Hack Series.
