### ISSUE TITLE
Clean up GitHub Teams

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#353]
There seem to unnecessary teams in in https://github.com/orgs/hackclub/teams

We should remove as many teams as possible (it seems like Contributors & Labs are unnecessary)

There may also be other cleanup that could be done here.

**Comment by jonleung** [comment]
Also, can we make sure we can tag all labs leaders in the `meta` and `hackclub` repos?

I can autocomplete @JevinSidhu in `hackclub` but not in `meta` and I'm not sure why because the teams look essentially the same except contributors:

**hackclub:**

![image](https://cloud.githubusercontent.com/assets/654941/11539932/9739193a-98de-11e5-8756-06e88816dead.png)

**meta:**

![image](https://cloud.githubusercontent.com/assets/654941/11539935/a0384592-98de-11e5-95df-354af1a97799.png)

**Comment by zachlatta** [comment]
Okay, I've deleted the Labs team and will submit a write-up to `hackclub/meta` on how GitHub teams will work.

**Comment by zachlatta** [comment]
Closed by #358.
