### ISSUE TITLE
Find a way to effectively integrate community created curriculum

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#354]
Currently mhesby, Bogidon, paked, Jevin and others are working on these great workshops and amysorto is working on these great powerpoint presentations—how do we consolidate them in a way so that the entire community can make use of these materials?

Current Problems (sorted in the order we should address them):

- We don't know how to organize and structure the content so that it's useful to leaders and members
- We as a community don't know how to determine the quality of new content (which is related the previous bullet point because you want it to be clear in the organizational structure of the content what has been used successfully and what hasn't)
- People don't know **where** and **how** to share their content with us
- People **don't even know** that they can share their content with us.
- People don't know **what** kinds of content are wanted

How can we fix the first problem first?

> We don't know how to organize and structure the content so that it's useful to leaders and members

/cc @zachlatta @MaxWofford

**Comment by MaxWofford** [comment]
For the time being, let's make sure to add the community workshops into our regular workshops folder

**Comment by paked** [comment]
I think this is the best way to handle community curriculum. Why should we
differentiate between official workshops anyway?

**Comment by MaxWofford** [comment]
Would anyone like to submit a PR to merge them?

**Comment by zachlatta** [comment]
100% agree. I'm happy to take point on this.

**Comment by jonleung** [comment]
@zachlatta sounds great! Do you want to create a separate issue for merging community workshops and our workshops? I want to leave this open until all the other questions are addressed.

**Comment by MaxWofford** [comment]
I believe this was closed by

https://github.com/hackclub/hackclub/commit/410af4d6c92fa8fca2b8c54a6fa709dcc531d9d6
https://github.com/hackclub/hackclub/commit/6f45dc9fd144931d391fd8b7e136d3c87e3acd29
https://github.com/hackclub/hackclub/commit/05e47825145e81ce3fce77fe04d22f218b928005

Feel free to reopen if it was not!
