### ISSUE TITLE
Add link to Medium blog to the footer of website

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#355]
/cc @zachlatta @MaxWofford

**Comment by zachlatta** [comment]
Shouldn't we actually link https://blog.hackclub.io?

**Comment by jonleung** [comment]
There's not content on that blog though... Wouldn't the medium be better because there's content?

**Comment by MaxWofford** [comment]
We should consolidate the medium and github blogs.

**Comment by jonleung** [comment]
^ :+1:

**Comment by zachlatta** [comment]
There's no content on our Medium blog either. https://medium.com/hack-edu is not our blog, it's our Medium publication where we syndicate content from members of our community.
