### ISSUE TITLE
Make sure that all of Cipher's workshops are in hackclub/hackclub:workshops

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#356]

**Comment by MaxWofford** [comment]
@jonleung what needs to be completed for this issue to be closed?

**Comment by jonleung** [comment]
@MaxWofford, reworked the scope of the issue by retitling the issue! Thanks!

**Comment by jonleung** [comment]
Moving this back to ideas because in terms of curriculum, we're currently focused on rebuilding the early workshops for Hack Club as opposed to getting as many workshops into our repository as possible.

As a side note, there are tons of valuable things that I'm currently learning from Cipher's workshops right now (such as bolding keywords) that I'm incorporating into these new early workshops.

**Comment by zachlatta** [comment]
:+1:

On Wed, Jan 13, 2016 at 8:55 PM, Jonathan Leung <notifications@github.com>
wrote:

> Moving this back to ideas because in terms of curriculum, we're currently
> focused on rebuilding the early workshops for Hack Club as opposed to
> getting as many workshops into our repository as possible.
>
> As a side note, there are tons of valuable things that I'm currently
> learning from Cipher's workshops right now (such as bolding keywords) that
> I'm incorporating into these new early workshops.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/356#issuecomment-171529632>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by MaxWofford** [comment]
@jonleung On the note of things like bolding keywords, make sure to update our styleguides as you go. I'm sure they can be massively improved by the changes!

**Comment by zachlatta** [comment]
Yup! Also don't forget that "coding words" (like "git", "index.html", and
shell commands) should be styled as inline code. There were a bunch of
issues in Cipher's workshops around that (though it's totally not their
fault because they weren't building them to follow our styleguide).

On Thu, Jan 14, 2016 at 1:18 AM, Max Wofford <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> On the note of things like
> bolding keywords, make sure to update our styleguides as you go. I'm sure
> they can be massively improved by the changes!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/356#issuecomment-171582102>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
Sounds good! I'll keep this in mind!

**Comment by zachlatta** [comment]
Going to go ahead and close this since it's no longer a priority since we created [our new curriculum plan](https://github.com/hackclub/meta#curriculum-plan).
