### ISSUE TITLE
I propose removing the following labels from hackclub/hackclub

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#367]
**hackclub/hackclub**

I propose removing the following labels from the hackclub repository:

- `enhancement`
  - it is completely unclear what this means and there are definitely lots of issues that have been created and will continue to be that are enhancements that are not labeled as such because it is unclear to the creator that they should label it `enhancement`.
- `beginner-friendly`
  - perhaps we should use `first-timers-only` instead? I think having both of these tags are redundant.
- `help-wanted`
  - this tag doesn't seem to be used. I'm down for trying to make this work though.
- `meeting` and `meta` having these labels seem unnecessary because being able to visually identify an issue is `meta` or `meeting` doesn't have any benefit

/cc @hackclub/hackclub

**Comment by MaxWofford** [comment]
I just cleared out the `blocking` label.

**Comment by MaxWofford** [comment]
and deleted all labels that didn't have any issues ever attatched

**Comment by zachlatta** [comment]
<3

**Comment by jonleung** [comment]
Any thoughts on the original comment?

**Comment by MaxWofford** [comment]
@jonleung: I'm down for closing those tags

**Comment by MaxWofford** [comment]
These tags have all been removed.

**Comment by zachlatta** [comment]
👍

--
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
<3
