### ISSUE TITLE
Hack Club Holiday Update

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#368]
_From @jonleung on December 10, 2015 23:28_

I think we should put out a holiday update on our progress and plans for 2016 to our

- funders
- advisors & supports

Thoughts @zachlatta?

_Copied from original issue: hackclub/hackclub#554_

**Comment by JevinSidhu** [comment]
Brian made this sweet Christmas themed logo for Cipher (https://www.facebook.com/projectcipher/photos/a.876682005731754.1073741825.864374390295849/949516158448338/?type=3&theater)!

If y'all did something like this for Hack Club, I think it'd be dope :)

**Comment by jonleung** [comment]
+1 to that ^

WHY IS BRIAN SUCH AN AMAZING DESIGNER! <3

**Comment by JevinSidhu** [comment]
Brian is a beast. :100:

**Comment by zachlatta** [comment]
@MaxWofford any ideas how a Christmas logo/theme might work? That would be
really fun.

Re: @jonleung, let's do this. I got a backer update from 80,000 hours and
we could follow their format for updates.

**Comment by jonleung** [comment]
@MaxWofford can we make it Chrismahanumiladunkwanzaa themed? I.e. prophet orpheus holding a Menorah, a Kinara, a Christmas tree, and the Arabic script for Milad un Nabi?

**Comment by MaxWofford** [comment]
@jonleung I'll see what I can do!

@hackclub/cipher's logos are amazing!  How can I learn to design like that?

**Comment by JevinSidhu** [comment]
Thanks Max :smile: 

Brian works on all our graphics stuff, can we get him added as member? https://github.com/nguyenbrian

**Comment by MaxWofford** [comment]
@JevinSidhu Invited!

**Comment by JevinSidhu** [comment]
:100: :+1:

**Comment by zachlatta** [comment]
We should have an ugly Christmas sweater family photo that we mail out to people.

**Comment by paked** [comment]
:+1: @zachlatta

**Comment by MaxWofford** [comment]
I can't do much right now, but here's a start:

![](http://i.imgur.com/bl6p0jb.gif)

**Comment by MaxWofford** [comment]
wow. that recorded really low quality. The original is svg, so it won't be a problem in the final.

**Comment by zachlatta** [comment]
Woah, this is amazing.

On Tue, Jan 5, 2016 at 4:14 PM, Max Wofford <notifications@github.com>
wrote:

> wow. that recorded really low quality. The original is svg, so it won't be
> a problem in the final.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/368#issuecomment-169175586>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by paked** [comment]
:+1: @MaxWofford <3

**Comment by jonleung** [comment]
As discussed with @zachlatta in person, assigning back to @zachlatta because he has more context with investors.

**Comment by zachlatta** [comment]
Thanks @jonleung. Will put this in my queue. @MaxWofford, can you send me a
final version of that GIF/SVG when you have a chance? Would love to put out
a blog post in addition to an email update to our contributors.

On Sun, Jan 10, 2016 at 3:57 PM, Jonathan Leung <notifications@github.com>
wrote:

> As discussed with @zachlatta <https://github.com/zachlatta> in person,
> assigning back to @zachlatta <https://github.com/zachlatta> because he
> has more context with investors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/368#issuecomment-170407302>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
@zachlatta I'll see what I can do.

**Comment by MaxWofford** [comment]
Looks like the holidays are gone! Can we close this @zachlatta ?

**Comment by zachlatta** [comment]
Yeah, good call. Closing.
