### ISSUE TITLE
Using asciicast for terminal commands  in workshops

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#371]
[![asciicast](https://asciinema.org/a/dad6a6dhsqpuynia8ok6xzv35.png)](https://asciinema.org/a/dad6a6dhsqpuynia8ok6xzv35?autoplay=1)

EDIT: We're already using a jsbin build system for our jsbins. We can extend it to our terminal commands.

**Comment by zachlatta** [comment]
The problem with using asciinema is that they're not playable from directly within the Markdown file on GitHub (as far as I know).

Is there a way to export a GIF from asciinema?

**Comment by MaxWofford** [comment]
It looks like asciinema-related tools aren't updated very regularly. There are ways to export GIF, but I don't think we can depend on them. Closing for now.

**Comment by zachlatta** [comment]
👍

--
Zach Latta
Hack Club | zach@hackclub.io
