### ISSUE TITLE
Write a message introducing yourself to everyone as a staff member

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#387]
Write a message to send to #announcements on Slack introducing yourself as a staff member :smiley:.

Comment on this post with it once you've written it so we can review it before posting to #announcements.

**Comment by paked** [comment]
> Hey guys, I'm Harrison. You may have seen me around the Slack (or on GitHub,
merging your pull requests!). I am a leader from Sydney, Australia and am
excited to announce I will be joining the Hack Club staff as an intern for the
next few weeks!

@zachlatta too brief?

**Comment by MaxWofford** [comment]
@paked :+1: You might want to include your github username.

**Comment by zachlatta** [comment]
Looks great! Let's add that you'll be in person with us and then post it. How's this?

> Hey guys, I'm Harrison. You may have seen me around the Slack (or on GitHub,
> merging your pull requests!). I am a leader from Sydney, Australia and am
> excited to announce I will be joining the Hack Club staff as an intern in San
> Francisco for the next few weeks! If you're in the Bay Area and want to meet
> up, just let me know -- I'll be here :-).

(I added the stuff about meeting up, feel free to remove that)

**Comment by paked** [comment]
> Hey guys, I'm Harrison. You may have seen me around the Slack (or on GitHub as @paked, merging your pull requests!). I am a leader from Sydney, Australia and am excited to announce I will be joining the Hack Club staff as an intern in San Francisco for the next few weeks! If you're in the Bay Area and want to meet up, just let me know -- I'll be here :jarjarbinks:.

@zachlatta @MaxWofford final call? :santa:

**Comment by zachlatta** [comment]
Looks perfect. Go ahead and post it!

![](http://i.giphy.com/3oEdv9HWXUUUd44Cc0.gif)

**Comment by paked** [comment]
https://starthackclub.slack.com/archives/announcements/p1450037923000243 posted xD
