### ISSUE TITLE
Refactor Twilio workshop to use jsbinctl

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#388]
Refactor the JS Bin examples in the Twilio workshop to be stored in directories in an `examples` directory within the workshop (ex. `examples/first_call`, `examples/sending_a_text_message`) and use `jsbinctl` for management.

Don't worry if the example on JS Bin is broken, just move their source code to the repository for the time being.

**Comment by paked** [comment]
@zachlatta shouldn't this be in hackclub/hackclub?

**Comment by zachlatta** [comment]
Ah, you're totally right. Migrating it now.

**Comment by zachlatta** [comment]
This issue was moved to hackclub/hackclub#561
