### ISSUE TITLE
Organise beginner friendly hack night

### ISSUE THREAD

**Issue by paked** [hackclub/meta#391]
Pitch: A Hack Night where want-to-be-contributors are paired with existing contributors and mentored through submitting their first pull requests.

Needed:

- An unhangout to host rooms
- A whole ton of `first-timer-only` issues
- Mentors
- Contributors

cc: @zachlatta

**Comment by MaxWofford** [comment]
:+1:

**Comment by paked** [comment]
We could try posting this to HH, a lot of people there are interested in getting into OSS.

**Comment by zachlatta** [comment]
:+1:

**Comment by MaxWofford** [comment]
Not sure if we still want to do this. Closing for the time being. If anyone would like to reopen it, please feel free.

**Comment by zachlatta** [comment]
I'd like to do this, but I'm not sure what our timeline would be for it. I'm on board with closing for the time being.

--
Zach Latta
Hack Club | zach@hackclub.io
