### ISSUE TITLE
Create JavaScript Styleguide

### ISSUE THREAD

**Issue by paked** [hackclub/meta#392]
Now that we have various amounts of JavaScript within our repositories, it would be beneficial to decide on a consistent style for it.

*discuss*

**Comment by MaxWofford** [comment]
+1

Some notable examples I've seen: https://github.com/feross/standard
https://github.com/airbnb/javascript

**Comment by paked** [comment]
@MaxWofford we're not really in a position to skip semicolons, because JS Bin...

**Comment by zachlatta** [comment]
Should we go ahead and close this? Seems like creating new curriculum is the current priority.

**Comment by zachlatta** [comment]
Going to go ahead and close this due to lack of response.

**Comment by zachlatta** [comment]
(Feel free to re-open if you'd like to continue discussion)
