### ISSUE TITLE
Purchase Food

### ISSUE THREAD

**Issue by paked** [hackclub/meta#406]
Needs to be completed once #404 is completed!

I'm down for anything, although it is probably best to play safe and go for either(?):

- Pizza
- Fruit

**Comment by ZucchiniZe** [comment]
What about having salads?

**Comment by JevinSidhu** [comment]
Don't forget drinks/water if you haven't already noted that :)

**Comment by zachlatta** [comment]
Let's get pizza + water for the time being because it's cheap and we're on a budget.

**Comment by paked** [comment]
@zachlatta rip salad

**Comment by zachlatta** [comment]
[image: Inline image 1]

**Comment by zachlatta** [comment]
![](http://i.giphy.com/xTk9ZN0nOx9HRuwfSM.gif)

**Comment by MaxWofford** [comment]
This was finished!


![](http://quickme.me/success.gif)
