### ISSUE TITLE
Swag Pack

### ISSUE THREAD

**Issue by paked** [hackclub/meta#410]
It may be nice to get a little Swag Pack going for our attendees. It may be a bit late, but we could potentially reach out to the other sponsors... See if they want to brand some high school students.

**Comment by paked** [comment]
thoughts @zachlatta?

**Comment by zachlatta** [comment]
Any ideas for what to include? Since we're so last minute on this, I'd bias for not doing this.

**Comment by MaxWofford** [comment]
We could just bring some stickers for the time being.

**Comment by zachlatta** [comment]
Let's go ahead and hand out stickers at the event. Closing for the time being so we can focus on driving registrations (see #407).
