### ISSUE TITLE
Create Hack Series

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#411]
- [x] Eventbright set up
- [x] Venue sponsor #403
- [x] Food sponsor #404
  - [x] Need to purchase the food #406
- [x] 32 student signups #407
- [x] Facilitators #408 
- [x] Confirm curriculum #409
- [x] Swag pack #410

**Comment by jonleung** [comment]
@MaxWofford, should someone be assigned to this issue?

**Comment by zachlatta** [comment]
Assigned myself!

**Comment by MaxWofford** [comment]
Closing this because Hack Series is done. Way to end on a high note!


![](http://quickme.me/success.gif)
