### ISSUE TITLE
Workshop shortlinks

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#412]
I propose we make shortlinks for our workshops using the https://workshops.hackclub.io link

Examples:

- `https://workshops.hackclub.io/portfolio` -> Portfolio workshop
- `https://workshops.hackclub.io/twilio` -> Twilio workshop

**Comment by MaxWofford** [comment]
:+1:

**Comment by zachlatta** [comment]
Closed by hackclub/hackclub#599.
