### ISSUE TITLE
Twilio demo that doesn't require internet

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#422]

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by MaxWofford** [comment]
It's in https://github.com/hackclub/twilio-demo

**Comment by MaxWofford** [comment]
Still in progress

**Comment by MaxWofford** [comment]
I take that back. it is done, but needs to be tested. I'll close this issue

**Comment by zachlatta** [comment]
Let's reopen this until it's tested and deployed :-).

**Comment by MaxWofford** [comment]
I've tested it locally. We might want to try it out with more than 2 numbers, but that's all I have.

**Comment by MaxWofford** [comment]
@zachlatta I don't have access to convox right now. Would you be interested in deploying this when you have the time?

**Comment by zachlatta** [comment]
Does this require Convox? Could it be hosted on GitHub pages (i.e. does it use our modified Twilio library that works on the frontend or the default one)?

--
Zach Latta
Hack Club | zach@hackclub.io

**Comment by MaxWofford** [comment]
@zachlatta It's a koa server.

**Comment by MaxWofford** [comment]
This protects us from scenarios like Downtown High School, where people who are demoing don't have access to internet.

**Comment by zachlatta** [comment]
Ah, fair. Can you take point on deploying this and setting up auto-deploy?
You should have enough access to the Convox to deploy this and for the
auto-deploy, you can basically just copy and paste what's in the circle.yml
of hackclub/packrat and modify it for the repo you made for the demo.

On Mon, Jan 11, 2016 at 1:14 PM, Max Wofford <notifications@github.com>
wrote:

> This protects us from scenarios like Downtown High School, where people
> who are demoing don't have access to internet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/422#issuecomment-170691796>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Is there a Hack Club official twilio account? My @hackclub.io twilio account was overextended and banned.

**Comment by jonleung** [comment]
@MaxWofford you can create a new Twilio account for this with our promo code.

**Comment by jonleung** [comment]
Wait, how does this work without an internet connection to Twilio?

**Comment by MaxWofford** [comment]
@jonleung The server records every number that sends an SMS to it. It inspects the contents of the message looking for a secret phrase. Once the demo-er sends the secret phrase in SMS to the Twilio number, everyone gets a reply SMS.

**Comment by MaxWofford** [comment]
The code should be pretty readable, feel free to check it out!

**Comment by paked** [comment]
@MaxWofford Updates on this?

**Comment by MaxWofford** [comment]
Oh, forgot to update the issue. @zachlatta removed the deployment from Convox because it was just  sitting there. If you ever need to spin it up, feel free to msg me.

**Comment by zachlatta** [comment]
Going to go ahead and close this :-).
