### ISSUE TITLE
Archive The Hack Series

### ISSUE THREAD

**Issue by paked** [hackclub/meta#442]
Now that we have concluded The Hack Series (THS) it makes sense to collate all of the information from the event into one single place. I suggest this be `hackclub/meta/the_hack_series` which has already become a sort of unofficial home for this information.

In terms of what needs to be moved I have made a list below:

- @jonleung's time schedules
- @jonleung's landing page
- Any texts we sent to students
- Communication protocols
- Scripts
- Non sensitive notes

**Comment by zachlatta** [comment]
I totally support this. Let's do it.

**Comment by paked** [comment]
@hackclub/staff  I'd really like to start getting this issue moving. I've assigned myself so I can now chase up all ye wrong doers.

To start, It'd be great to get everyones notes (preferably censored, ie. no sensitive information) of whichever cohorts they were able to note take for.

@zachlatta I'd like to have a note somewhere about the sign on the door, also it'd be great to have the text and twilio script you used to send out the reminder message 
(that worked really well).

@jonleung You have your landing page and schedule still in the hackclub/hackclub repository. I know you have quite a workload at the moment, perhaps delegate this to @MaxWofford or myself.

@MaxWofford The email you sent to the Hack Camp participants is already in the repository, however I'd just like to be sure that we have *everything*.

**Comment by MaxWofford** [comment]
@paked Thanks for getting this going! I can confirm that was the only email sent out. If I find any notes, I'll add them after everything is archived.

**Comment by zachlatta** [comment]
I've gone ahead and submitted #446 and #447 to add a event protocol that includes having a sign on the door and the SMS reminder script :-).

**Comment by jonleung** [comment]
@paked, if you could do me a favor and take lead on

> @jonleung You have your landing page and schedule still in the hackclub/hackclub repository. I know you have quite a workload at the moment, perhaps delegate this to @MaxWofford or myself.

that would be amazing!

Thanks for pushing us forward on this!

**Comment by paked** [comment]
Closing this because everything has been merged in! Good job team!
