### ISSUE TITLE
Apply to the Google RISE Awards

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#445]
https://www.google.com/edu/resources/programs/google-rise-awards/

A few people have recommended we apply and it seems to be the sort of grant that's right up our ally. Let's apply to this. Deadline is **February 19th, 2016**.

**Comment by paked** [comment]
@zachlatta Yo, this deadline is approaching really damn fast!

**Comment by MaxWofford** [comment]
![](https://i.imgur.com/vBHDsj7.jpg)

**Comment by zachlatta** [comment]
Thanks for the reminder guys :-).

I've assigned to @jkwok91. Will work with her to get this done.

On Mon, Feb 15, 2016 at 2:27 PM, Max Wofford <notifications@github.com>
wrote:

>
> <https://camo.githubusercontent.com/7070c7d972a48769eef61fdb866ae4b87d2a68f4/68747470733a2f2f692e696d6775722e636f6d2f76424844736a372e6a7067>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/445#issuecomment-184423186>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Getting started on this ASAP.
