### ISSUE TITLE
Archive The Hack Series landing page/schedule

### ISSUE THREAD

**Issue by paked** [hackclub/meta#448]
Related to #442

**Comment by zachlatta** [comment]
Which landing page/schedule are you referring to?
https://github.com/hackclub/hack-series is already deprecated.

On Thu, Dec 31, 2015 at 4:05 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Related to #442 <https://github.com/hackclub/meta/issues/442>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/448>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by MaxWofford** [comment]
@paked What do we need to do to close this?

**Comment by paked** [comment]
@MaxWofford I need to close #449 :D
