### ISSUE TITLE
Write a spring semester update to our clubs

### ISSUE THREAD

**Issue by jonleung** [hackclub/meta#458]
_From @jonleung on January 6, 2016 20:20_

_Copied from original issue: hackclub/hackclub#640_

**Comment by jonleung** [comment]
_From @zachlatta on January 6, 2016 21:15_

Oh whoops, didn't mean to assign myself. Sorry about that!

**Comment by jonleung** [comment]
Here is my preliminary outline of this letter.

```md
- It's been an exciting year
- It has been amazing working with you
- We have learned a lot and not it's time to onboard all these new clubs
- In the next two months, we are focusing on growth
- We want to add 50 additional clubs to Hack Club
  - We're focusing on getting the initial curriculum right so this means that we might not have curriculum that's targeted for you
  - But we believe that you'll be able to figure it out
  - We're putting together a Hack Club guide, please leave comments HERE about what your thoughts are
  - You are Hack Club's inaugural class, as you gain more experience it's time to help new club leaders
    - Make people feel welcome
    - They'll be reaching out for questions, help them out
- Let's make 2016 amazing
```

Going to write the actual letter now.

**Comment by jonleung** [comment]
_From @zachlatta on January 11, 2016 0:58_

:+1:

On Sun, Jan 10, 2016 at 4:26 PM, Jonathan Leung <notifications@github.com>
wrote:

> Here is my preliminary outline of this letter.
>
>
>    - It's been an exciting year
>    - It has been amazing working with you
>    - We have learned a lot and not it's time to onboard all these new
>    clubs
>    - In the next two months, we are focusing on growth
>    - We want to add 50 additional clubs to Hack Club
>       - We're focusing on getting the initial curriculum right so this
>       means that we might not have> curriculum that's targeted for you
>       - But we believe that you'll be able to figure it out
>       - We're putting together a Hack Club guide, please leave comments
>       HERE about what your>
>       - You are Hack Club's inaugural class, as you gain more experience
>       it's time to help new club> leaders
>       - Make people feel welcome
>       - They'll be reaching out for questions, help them out
>    - Let's make 2016 amazing
>
> Going to write the actual letter now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/640#issuecomment-170409637>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
@zachlatta, do you have a preference for who sends this out? I'm happy to do it!

**Comment by zachlatta** [comment]
Either of us works for me. Let's plan on having you send it out since you're writing it.

It'd be great if you could run it by me before sending it out though.

--
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
@zachlatta, I'm going to opt to follow [this comment](https://github.com/hackclub/meta/pull/459#issuecomment-170621937) over [this one](https://github.com/hackclub/meta/issues/458#issuecomment-170622604). I've went ahead and submitted a pull request with your version of the letter in #459. I've assigned you to merge in that pull request.

Just to re-confirm, as you stated in here, https://github.com/hackclub/meta/pull/459#issuecomment-170621937, you will send out this letter to club leaders yeah?

**Comment by zachlatta** [comment]
Yup, sounds good. Once the pull request is updated and merged.

On Mon, Jan 11, 2016 at 10:20 AM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, I'm going to opt to follow this
> comment <https://github.com/hackclub/meta/pull/459#issuecomment-170621937>
> over this one
> <https://github.com/hackclub/meta/issues/458#issuecomment-170622604>.
> I've went ahead and submitted a pull request with your version of the
> letter in #459 <https://github.com/hackclub/meta/pull/459>. I've assigned
> you to merge in that pull request.
>
> Just to re-confirm, as you stated in here, #459 (comment)
> <https://github.com/hackclub/meta/pull/459#issuecomment-170621937>, you
> will send out this letter to club leaders yeah?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/458#issuecomment-170640607>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
I just updated the pull request with your edits!
