### ISSUE TITLE
Drive 5 more applications to Hack Club

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#483]
@paked and I are having a competition this week to see who can drive the most applications. We've set the bar for each of us to 5. This issue is to track the applications I'm driving.

**Comment by paked** [comment]
![game_on](https://cloud.githubusercontent.com/assets/8407370/12569755/bd484d4a-c425-11e5-8182-61bccaf09180.gif)

**Comment by zachlatta** [comment]
Got 10 applications since I made this issue, closing.

**Comment by jonleung** [comment]
<3
