### ISSUE TITLE
SSL Broken on Latest Google Chrome

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#491]
![screen shot 2016-02-11 at 8 49 25 pm](https://cloud.githubusercontent.com/assets/992248/12999897/042038e6-d109-11e5-8516-eb6d3fe72113.png)

Seems to be because the certificate chain isn't being sent over as well. We need to fix this ASAP.

**Comment by paked** [comment]
:+1: Please fix ASAP

**Comment by MaxWofford** [comment]
@zachlatta Is this still happening?

**Comment by zachlatta** [comment]
Gah, I gotta do this. Will try to get to tomorrow.

On Thu, Mar 3, 2016 at 11:48 AM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Is this still happening?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/491#issuecomment-191932367>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Fixed!

**Comment by MaxWofford** [comment]
Woooo!
