### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by jkwok91** [hackclub/meta#497]
I previously created some Hack Club banners in https://github.com/hackclub/hackclub/issues/670. @MrCodeCollector mentioned that he'd like something that looks more like the following:

![bad pixel art](https://cloud.githubusercontent.com/assets/2666337/13124952/f6fbe386-d577-11e5-8683-9df67444d5b4.png)

But this needs some more work.

**Comment by MaxWofford** [comment]
so much yes

**Comment by MaxWofford** [comment]
@jkwok91 Do you have other sketches of this?

**Comment by jkwok91** [comment]
Closing; [existing banners](https://blog.hackclub.com/2016/02/16/we-have-graphics/) will suffice for now.
