### ISSUE TITLE
Hack Club Socks

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#499]
I think it is absolutely imperative that Hack Club has custom socks. See http://custom.sockclub.com.

**Comment by paked** [comment]
ILL BUY SOME. SO MUCH NEED.

**Comment by paked** [comment]
@kwok I think you may have misinterpreted what I said here. I meant to
imply that I would buy them if they were put on sale, not order them from
the sock company.

**Comment by MaxWofford** [comment]
This is a fantastic idea, but I'm going to close it because it looks like there haven't been any updates recently.
