### ISSUE TITLE
Fast Forward Application

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#503]
**Website:** http://www.ffwd.org/
**Application deadline:** April 1, 2016
**Program start date:** July 6, 2016
**Grant size:** $25,000, mentorship, and demo day

---

Let's apply to the Fast Forward accelerator. It's kinda like YC, but for nonprofits. Quick blurb from them:

> In 2015, our 14 teams impacted the lives of 3.4 Million people, wrote 1.5
> Million lines of code, and had 53% median revenue growth. 79% were founded by
> women and people of color.
>
> Fast Forward is an accelerator exclusively for tech nonprofits. Over 13 weeks,
> fellows received a $25,000 grant, mentorship from + 100 tech and philanthropic
> leaders, and 100 hours of pro bono support and training. The program
> culminates in a Demo Day during which the nonprofits pitch to 200 funders and
> philanthropists. The program starts July 6th in San Francisco. ONLY NONPROFITS
> are eligible for this program. Apply before April 1st here: Fast Forward's
> 2016 Accelerator application

**Comment by ssun098** [comment]
Note to self: put together both organization & club leader perspectives

**Comment by paked** [comment]
:+1:

**Comment by zachlatta** [comment]
Quick overview of our current stats (let me know if you have any questions about the data).

![tmp](https://cloud.githubusercontent.com/assets/992248/13278070/4d359d50-da82-11e5-9b27-fb5bef6f2f87.png)

**Comment by MaxWofford** [comment]
> Application deadline: April 1, 2016
@ssun098 can we close this?

**Comment by ssun098** [comment]
Yep! It's all done

**Comment by zachlatta** [comment]
:ok_hand:

On Tue, Apr 19, 2016 at 9:25 PM, Selynna Sun <notifications@github.com>
wrote:

> Closed #503 <https://github.com/hackclub/meta/issues/503>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/503#event-633963989>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
