### ISSUE TITLE
Classy Grant Application

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#504]
We just completed our application tonight for the [Classy Awards](https://www.classy.org/collaborative). Right now, everything we wrote for this grant is in their custom grant software.

Can you create a Markdown file with all of our answers in the `applications/` folder?

**Comment by jkwok91** [comment]
RAAAAAAARRARARAR

**Comment by jkwok91** [comment]
Update: I emailed to ask if we could ever view our application, and Classy said it will be available after judging.

**Comment by zachlatta** [comment]
👌

**Comment by MaxWofford** [comment]
@jkwok91 What needs to get done to close this?

**Comment by jkwok91** [comment]
@zachlatta Has Classy released the submission text?

**Comment by zachlatta** [comment]
@MaxWofford: We need classy to release the application's text.

@jkwok91: No :-(. I emailed them about it and they said we need to wait
until review for all applications is over before we can access our
application.

On Tue, Apr 19, 2016 at 8:13 PM, JESSICA <notifications@github.com> wrote:

> @zachlatta <https://github.com/zachlatta> Has Classy released the
> submission text?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/504#issuecomment-212229199>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Continuing to follow-up with them on this. Pretty annoying that they still haven't released the application text.

**Comment by zachlatta** [comment]
Okay, Classy is garbage. Let's close this now and give up.

They still haven't given us the grant back.
