### ISSUE TITLE
Create Hack Club one sheet for school administration

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#507]
We have a club in Illinois that was just reprimanded by their school administration for being associated with Hack Club. They're afraid of their name and, as a result, the club isn't allowed to associate with us until they get a better idea of what Hack Club is. They didn't get enough information from our website to trust us (which makes sense, our website is currently pretty lacking).

If they're a public school and in the United States, this is actually illegal because of https://en.wikipedia.org/wiki/Equal_Access_Act. That said, I think there's a better way to solve this.

Let's create a "one sheet" with details on what Hack Club is and what our clubs do. I've attached an example one sheet for [CS First](https://www.cs-first.com/). [Click here](https://github.com/hackclub/meta/files/157496/General.Info.Flyer-twosided.pdf) for it.

**Comment by jkwok91** [comment]
There is now one in the Dropbox. There may be iterations in the future.

**Comment by zachlatta** [comment]
Can you submit it to this repo?

On Sat, Mar 5, 2016 at 3:07 PM, JESSICA <notifications@github.com> wrote:

> Closed #507 <https://github.com/hackclub/meta/issues/507>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/507#event-578943533>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
In what directory?

**Comment by MaxWofford** [comment]
We could make a `resources` directory that includes our one sheets and logos.

**Comment by zachlatta** [comment]
👍
