### ISSUE TITLE
Investigate getting our own 501(c)(3) status

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#521]
We're planning on parting ways with our fiscal sponsor in June 2016 and need to either get our own 501(c)(3) status or find a new fiscal sponsor.

This issue is to track investigating getting our own 501(c)(3) status (i.e. is that even feasible in this timeframe?).

**Comment by zachlatta** [comment]
Okay, so I reached out to the lawyer that I've been working with and they don't have any bandwidth to work with us to get our 501(c)(3) right now. I'm getting a referral for another lawyer from a friend.

**Comment by zachlatta** [comment]
Update: I talked with another lawyer last week, but the quote they gave me was insane. The search continues...

**Comment by zachlatta** [comment]
Talked with a friend that runs a nonprofit yesterday. They're going to intro me to a lawyer they know.

**Comment by zachlatta** [comment]
And they worked out! Sending along the official paperwork tomorrow, we're set for getting our 501(c)(3).

Closing :raised_hands:.

**Comment by MaxWofford** [comment]
Nice @zachlatta! Hearing this made my day :)

![good_day](https://cloud.githubusercontent.com/assets/5891442/15237786/7b6f6eb6-189f-11e6-83b7-293dba5396f3.gif)
