### ISSUE TITLE
Get first date confirmed for Shasta club

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#522]
@jkwok91 and I are starting a Hack Club at [Summit Shasta](http://www.summitps.org/schools/california/summit-shasta) to build out the [new curriculum plan](https://github.com/hackclub/meta#curriculum-plan).

Before we can have a first meeting there, we need to do two things:

- [x] Send over volunteer paperwork
  - [x] @zachlatta
    - [x] Get Live Scan thumbprint done
    - [x] Get a TB test
  - [x] @jkwok91
    - [x] Get Live Scan thumbprint done
    - [x] Get a TB test
- [x] Find a teacher/faculty member that's willing to host us after school
- [x] Find a leader at the school

**Comment by jkwok91** [comment]
We did these things so I am closing this.

**Comment by jkwok91** [comment]
First date is April 28th
