### ISSUE TITLE
Organize Hack Night for April 29th

### ISSUE THREAD

**Issue by jkwok91** [hackclub/meta#530]
This is an issue to track the planning for Hack Night on Friday, April 29th. It's both to remind me what needs to be done, and update everyone else on the progress.

Todo:
- [x] Set logistics
  - [x] Place: [partytime.hackclub.com](https://partytime.hackclub.com)
  - [x] Time: 5PM
  - [x] Theme: GOODNIGHT MOOOOOOON YOOOOO
- [x] Make initial announcement
- [x] Make poster
- [x] Get at least ~~three~~ two in-person meetups happening (@zachlatta's responsibility)
- [x] Host
  - [x] Buy pizza
- [x] Follow up
  - [x] Feedback form
  - [ ] ~~Send PRIZES!!!!~~

**Comment by paked** [comment]
I don't think having multiple themes is a good idea. Not quite sure why, it just feels... Off.

**Comment by jkwok91** [comment]
In that case, how about a poll?

**Comment by paked** [comment]
Works for me!

**Comment by zachlatta** [comment]
Update: Jessica and I were talking last night and she came up with an
awesome theme. No polling for now, wait for the announcement ;-).

On Sat, Apr 16, 2016 at 9:38 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Works for me!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/530#issuecomment-210955376>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Closing because Hack Night has happened!
