### ISSUE TITLE
Create Hack Night stickers

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#535]
Stickers to mail out to people who participated in a Hack Night.

**Comment by jkwok91** [comment]
Working on this 🔨

**Comment by paked** [comment]
What if there were "Hack Night" badges, so each Hack Night had a sticker corresponding to its theme and you got to collect them... Like gym badges in pokemon!

**Comment by zachlatta** [comment]
Just you wait ;-).

On Thu, Apr 21, 2016 at 11:54 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> What if there were "Hack Night" badges, so each Hack Night had a sticker
> corresponding to its theme and you got to collect them... Like gym badges
> in pokemon!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/535#issuecomment-213292149>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
I have created them. Closing this issue.

**Comment by MaxWofford** [comment]
@jkwok91 where are they currently?
