### ISSUE TITLE
Rename Google organization

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#539]
It looks like our Google organization is still named hackEDU.
![screenshot_2016-04-24_19 28 14](https://cloud.githubusercontent.com/assets/5891442/14771239/b55d30fa-0a52-11e6-83b9-c5dd5ecca069.png)

**Comment by zachlatta** [comment]
Yeah, this is actually a limitation of Google Apps. We've changed the name of the organization to "Hack Club", but we can't change the name of the "top level organizational unit" (which is what you're seeing in that dropdown). See https://support.google.com/a/answer/178186?hl=en for more details.
