### ISSUE TITLE
Create a "What is GitHub?" one-sheet

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#545]
A bunch of school districts have GitHub blocked and I think it'd be helpful to have a one-sheet on GitHub we could distribute to administration.

One idea for how to pitch it is "GitHub is how programmers write code together. Trying to write code without GitHub is like trying to write an essay without Google Docs or Microsoft Word. It's technically possible, but you're severely impaired."

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by zachlatta** [comment]
Just a note, but we're going to want this for the upcoming school year.

**Comment by MaxWofford** [comment]
@zachlatta @ssun098: Who should we assign this to?

**Comment by ssun098** [comment]
Moving this to unsorted until we get this reassigned to an active team member

**Comment by MaxWofford** [comment]
@CoolBeans19 Could you comment with a link to the PR that closes this issue?
