### ISSUE TITLE
Add license to font used in logo

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#550]

**Comment by zachlatta** [comment]
Why in Dropbox? Isn't the main file in the meta repo?

On Tue, May 3, 2016 at 6:48 PM, Max Wofford <notifications@github.com>
wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/550>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
@zachlatta Thanks for catching that!

**Comment by MaxWofford** [comment]
#552 closes this

**Comment by zachlatta** [comment]
Just waiting on you to fix my comments in #552.

**Comment by MaxWofford** [comment]
Closed by #552
