### ISSUE TITLE
Moving away from using Dropbox to store assets

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#553]
@jkwok91 and @MaxWofford, I know both of you have been using our team Dropbox to store logos and other Hack Club assets.

What are your thoughts on moving everything into GitHub repos? We could either put them in `hackclub/meta` or create a new repo for assets.

**Comment by MaxWofford** [comment]
Totally down to using git to store major versions of our assets.

I'd still like to use Dropbox to keep a pool of the sketchy, early WIP stuff though. Using git with to track so many changes when I really only need the current version is a hassle.

**Comment by jkwok91** [comment]
Can we not do migrationy stuff while there are more pressing matters at hand

**Comment by zachlatta** [comment]
I think these sorts of incremental improvements are important, but I also
agree that we currently have more pressing matters at hand. Let's
de-prioritize this task until we have a venue and enough sign-ups secured
for Hack Camp.

On Wed, May 11, 2016 at 1:01 PM, JESSICA <notifications@github.com> wrote:

> Can we not do migrationy stuff while there are more pressing matters at
> hand
>
> On Wednesday, May 11, 2016, Max Wofford <notifications@github.com> wrote:
>
> > Totally down to using git to store major versions of our assets.
> >
> > I'd still like to use Dropbox to keep a pool of the sketchy, early WIP
> > stuff though. Using git with to track so many changes when I really only
> > need the current version is a hassle.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hackclub/meta/issues/553#issuecomment-218571439>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/meta/issues/553#issuecomment-218572946>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Going to go ahead and close this issue due to it not being a priority.
