### ISSUE TITLE
Redesign Hack Club one-sheet

### ISSUE THREAD

**Issue by jkwok91** [hackclub/meta#556]
It needs much improvement.

**Comment by zachlatta** [comment]
Here are the two one-sheets we have so far:

[3818314437077982764.pdf](https://github.com/hackclub/meta/files/271565/3818314437077982764.1.pdf)
[9671487326761620072.pdf](https://github.com/hackclub/meta/files/271564/9671487326761620072.pdf)

**Comment by zachlatta** [comment]
And here's an updated back and white one with the latest stats (and correct comparison stats):

[onesheet_bw_updated.pdf](https://github.com/hackclub/meta/files/272620/onesheet_bw_updated.1.pdf)

**Comment by zachlatta** [comment]
I submitted #564 to make a basic version. Still waiting on @jkwok91 to make a final version.

**Comment by zachlatta** [comment]
Hey, any updates on this?

**Comment by ssun098** [comment]
Moving this to unsorted until we get this reassigned to an active team member

**Comment by CoolBeans19** [comment]
@zachlatta @MaxWofford @jkwok91 I will scour the Google Photos for photos to use on the onesheet, but if you want me to use the same ones I would appreciate getting the files. Also please tell inform if you do not want any pictures.

**Comment by CoolBeans19** [comment]
nvm found the picture
