### ISSUE TITLE
Pick a shade of red

### ISSUE THREAD

**Issue by LabLayers** [hackclub/meta#560]
I've noticed that you're using different shades of red through your sites...

![image](https://cloud.githubusercontent.com/assets/607807/15492308/ddf9eccc-2147-11e6-959e-c208c036392a.png)

So I set on a mission to find as many different shades of red as I could find. After 10 minutes of browsing around. I was able to sample 8 different shades of non-gradient red across your websites and hackclub/meta/logos.

![image](https://cloud.githubusercontent.com/assets/607807/15492355/8784c866-2148-11e6-837f-3d5b82827cd6.png)

The gradients seemed to be consistent across most of your marketing material but the angle may be different (for valid reasons like wide banners in your logos folder)

Which shade of red (and/or gradient) is it? Pick one and keep it consistent. 😉

**Comment by LabLayers** [comment]
I personally like the gradient and I could to do something special with it on the website.

**Comment by LabLayers** [comment]
Furthermore, it would help to create some sort of design style guide. Other things like fonts are not consistent at all across your materials.

**Comment by jkwok91** [comment]
@LabLayers: I LOVE that you're doing this preliminary research/investigation. Unfortunately I think I am guilty of most of the problems you are referring to.

I've been using `rgb(255, 75, 85)` (or `#ff4b55`) for the red, and `rgb(232, 78, 116)` (or `#e84e74`) for the purple. @MaxWofford confirm?
As for typefaces, I've been trying out different stuff, for fun? Ha. Definitely haven't been sticking to the Amaranth.

**Comment by zachlatta** [comment]
Totally agree with the inconsistency being a problem. Until now, design consistency hasn't been a priority, but now it's starting to cause problems and it's time we change that. @coolbeans19 also brought up the need for a design style guide.

Here's my current understanding of things (@MaxWofford will be able to fill in where I can't):

- [This is our latest logo (as of the time of this comment)](https://github.com/hackclub/meta/blob/f6e988174a3437b7854ef549baf0625bdb6e4dba/logos/hack_club_red_text.svg) and it has our main gradient in it – it's an Inkscape SVG, so you can get all of its source info (including the gradient's start and end colors) if you open it in Inkscape
  - This logo has a modified Amaranth in it. I believe @MaxWofford combined Open Sans and Amaranth, but he'd need to clarify.
- [Our latest letter logo (again, as of the time of this comment)](https://github.com/hackclub/meta/blob/f6e988174a3437b7854ef549baf0625bdb6e4dba/logos/hack_club_letter.svg) uses a different gradient. That's simply a result of my incompetence: the above logo's gradient is the correct one.
- We started with a slightly dull pastel red (`#d3595d`) and later converted to a slightly brighter red in https://github.com/hackclub/website/commit/c0660cadc0bc8c9eedbab593b6691f3193696fa3. The variety of colors used is simply a result of a standard (or failing to update colors, in the case of https://shipped.hackclub.com/)

**Comment by MaxWofford** [comment]
@jkwok91: Can confirm; that is one of the colors for the purple!

@zachlatta: Yes, Amaranth is the base for our logo. The `H` is modified Amaranth and the 'K' is modified Open Sans.

@LabLayers: @zachlatta and @jkwok91 pretty much covered everything I can think of.

**Comment by zachlatta** [comment]
@LabLayers did you end up picking a shade of red to go with? We could standardize that across everything.

**Comment by zachlatta** [comment]
Ping ping.

**Comment by LabLayers** [comment]
After a bit of discussion in the slack a while back, I decided to go with a slightly bolder/vibrant shade of red, #E42D40 in my mockups.

**Comment by MaxWofford** [comment]
@LabLayers @zachlatta Can this issue be closed?
