### ISSUE TITLE
Create stickers with Hack Club's logo

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#566]
Just the file over at https://github.com/hackclub/meta/blob/master/logos/hack_club_red_text.svg. We could make it a transfer sticker or go for the custom cutout around the letters.

Requested by @bhargav-y.

**Comment by MaxWofford** [comment]
Transfer would look fantastic on a black laptop

**Comment by MaxWofford** [comment]
This issue was moved to hackclub/hackclub#1011
