### ISSUE TITLE
Find venue for Hack Series/Demo Night

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#567]
Goal is to get it in by Thursday

**Comment by ssun098** [comment]
love segment <3 <3

**Comment by zachlatta** [comment]
Segment is incredible.

On Mon, Jun 27, 2016 at 4:13 PM, Selynna Sun <notifications@github.com>
wrote:

> love segment <3 <3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/567#issuecomment-228903742>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-K70HM1z9MIZymda6P1142cfm0B-ks5qQFkdgaJpZM4I6CLY>
> .
>



-- 
Zach Latta
Hack Club | zach@hackclub.com
