### ISSUE TITLE
Create Facebook and Eventbrite events for Demo Night

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#569]
- [x] Demo Night
  - [x] Facebook
  - [x] Eventbrite

**Comment by ssun098** [comment]
[Demo Night Eventbrite](https://www.eventbrite.com/e/hack-club-demo-night-tickets-26230059815)
[Demo Night Facebook](https://www.facebook.com/events/249802872065631/ )

**Comment by MaxWofford** [comment]
I'm splitting the Hackshops requirements off into https://github.com/hackclub/meta/issues/579.

**Comment by ssun098** [comment]
Closing this because it's done
