### ISSUE TITLE
Drive signups for Hack Series

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#572]
- [x] Promote on social media
  - [x] Facebook 
  - [x] Twitter
- [x] Reach 10 signups
   - [x] Session 1
   - [x] Session 2

**Comment by MaxWofford** [comment]
@ssun098: any updates on social media?

**Comment by ssun098** [comment]
Everything has been posted on Facebook and Twitter, we just need to keep posting occasionally

**Comment by ssun098** [comment]
Reached out signups goal!

**Comment by zachlatta** [comment]
Ayyyy, :raised_hands:!

On Sun, Jul 10, 2016 at 3:20 PM, Selynna Sun <notifications@github.com>
wrote:

> Reached out signups goal!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/572#issuecomment-231614342>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-NpB6uHmSKlYV2_o14X2NixXTL3Rks5qUXA7gaJpZM4I_sHT>
> .
>



-- 
Zach Latta
Hack Club | zach@hackclub.com
