### ISSUE TITLE
Create Facebook and Eventbrite events for Hack Series

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#579]
- [x] Hack Series 
  - [x] Facebook
  - [x] Eventbrite

**Comment by ssun098** [comment]
[Facebook](https://www.facebook.com/events/1785939154973659/#)
[Eventbrite](https://www.eventbrite.com/e/hack-series-tickets-26339922417)

**Comment by zachlatta** [comment]
Ah, love the new name.

On Wed, Jun 29, 2016 at 4:34 PM, Max Wofford <notifications@github.com>
wrote:

>
>    - Hack Series
>       - Facebook
>       - Eventbrite
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/579>, or mute the thread
> <https://github.com/notifications/unsubscribe/AA8j-Ea9neBHooixZN49Y-tNWFQkUrL6ks5qQwD1gaJpZM4JBq4L>
> .
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by ssun098** [comment]
i can feel the sarcasm

**Comment by ssun098** [comment]
@zachlatta we actually decided not to change the name :P

**Comment by zachlatta** [comment]
Oh really? I actually liked Hack Basics.

On Wed, Jun 29, 2016 at 6:23 PM, Selynna Sun <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> we actually decided not to
> change the name :P
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/579#issuecomment-229535461>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-P7H5Pi_aPq1AXV2ecZ2Q_089NdWks5qQxqSgaJpZM4JBq4L>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
(or HackBasics, I guess)

On Thu, Jun 30, 2016 at 3:23 PM, Zach Latta <zach@zachlatta.com> wrote:

> Oh really? I actually liked Hack Basics.
>
> On Wed, Jun 29, 2016 at 6:23 PM, Selynna Sun <notifications@github.com>
> wrote:
>
>> @zachlatta <https://github.com/zachlatta> we actually decided not to
>> change the name :P
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/hackclub/meta/issues/579#issuecomment-229535461>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AA8j-P7H5Pi_aPq1AXV2ecZ2Q_089NdWks5qQxqSgaJpZM4JBq4L>
>> .
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by ssun098** [comment]
Our logic was that since we already marketed Hack Series last time, people
might recognize the name this time so it wouldn't be worth rebranding. I
dunno, we might rebrand next time?
