### ISSUE TITLE
Find mentors for Hack Series

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#580]
This can be closed once our on-boarding process is documented in this repo and 3 mentors are confirmed and have been on-boarded for each time-slot of Hack Series.

**Comment by ssun098** [comment]
@MaxWofford are we good for closing this? seems like we have enough mentors for the event

**Comment by MaxWofford** [comment]
@ssun098 Is it recorded somewhere?

**Comment by ssun098** [comment]
No, I wasn't sure where it'd be recorded

**Comment by ssun098** [comment]
@MaxWofford https://docs.google.com/spreadsheets/d/1wjpGz61ODzoQDxdTI5Svat09mSfoa-0Ady6EjWlnDQ4/edit#gid=0
