### ISSUE TITLE
Update series.hackclub.com

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#582]
This can be closed once series.hackclub.com directs to the 2016 Eventbrite page.

**Comment by MaxWofford** [comment]
Currently blocking on having an Eventbrite page https://github.com/hackclub/meta/issues/579

**Comment by MaxWofford** [comment]
No longer blocking on #579 because I've got the Eventbrite URL (https://www.eventbrite.com/e/hack-series-tickets-26339922417).

**Comment by MaxWofford** [comment]
@zachlatta Would you please direct series.hackclub.com to https://www.eventbrite.com/e/hack-series-tickets-26339922417?

**Comment by MaxWofford** [comment]
@zachlatta Just a quick ping on this

**Comment by ssun098** [comment]
@zachlatta another ping

**Comment by zachlatta** [comment]
Done, so sorry for the delay. Really not cool of me.
