### ISSUE TITLE
Get food for 2nd session of Hack Series

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#584]
need food for 2nd session and 3rd session

**Comment by ssun098** [comment]
@MaxWofford Tejas is going to ask about covering the session we don't have food for, so we probably won't know until next week if we'll need to get more food for the ,2nd session

**Comment by MaxWofford** [comment]
Next week is when Hack Series is running.

**Comment by ssun098** [comment]
Sorry I mean by Monday or Tuesday or something

**Comment by ssun098** [comment]
Waiting for response from Tejas

**Comment by ssun098** [comment]
update: need to buy food for hackers in 2nd session Saturday

**Comment by zachlatta** [comment]
Can we just say we're not going to provide food? Seems like more work.

On Thu, Jul 14, 2016 at 12:02 PM, Selynna Sun <notifications@github.com>
wrote:

> update: need to buy food for hackers in 2nd session Saturday
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/584#issuecomment-232760932>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-M7BhdFlNgRl5d_gRr1gz8U5suzrks5qVofTgaJpZM4JBsDv>
> .
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
We can just get pizza delivered, shouldn't take more than 10 minutes.

**Comment by ssun098** [comment]
IT seems kinda weird to provide for one session and not the other?

**Comment by MaxWofford** [comment]
Segment provided us with enough food for both sessions.
