### ISSUE TITLE
Find someone to do Short-Talk for Demo Night

### ISSUE THREAD

**Issue by MrCodeCollector** [hackclub/meta#585]

**Comment by ssun098** [comment]
@zachlatta do you have any updates on this?

**Comment by MaxWofford** [comment]
@zachlatta Let's reach out to Bogidon

**Comment by zachlatta** [comment]
Update: reached out to @Bogidon, but he can't make it due to traveling. Will reach out to a few more people.

**Comment by ssun098** [comment]
@MaxWofford can this be closed if Stefan is confirmed?

**Comment by MaxWofford** [comment]
Let's do it.
