### ISSUE TITLE
Update demo-night.hackclub.com

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#586]
https://www.eventbrite.com/e/hack-club-demo-night-tickets-26230059815

**Comment by ssun098** [comment]
https://www.eventbrite.com/e/hack-club-demo-night-tickets-26230059815

**Comment by MaxWofford** [comment]
@zachlatta Would you please create this sub-domain?

**Comment by ssun098** [comment]
@zachlatta pinging again

**Comment by zachlatta** [comment]
Done! I am *so* sorry for the delay – not cool of me.
