### ISSUE TITLE
Decide on a date for Hack Night

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#589]
This issue can be closed once someone comments on this issue with the date we're running it.

**Comment by zachlatta** [comment]
How's this going? Should @raysarebest be assigned to this?

**Comment by raysarebest** [comment]
According to the poll in the Slack, it looks like Friday is a solid recurring day to do it, as that's the number winning out last time I checked. That being said, I'll have to be rather late to this Friday's (7/15, as it turns out), because that's my grandfather's birthday, and I'll be out to dinner with him for the first part of it

**Comment by zachlatta** [comment]
Do you want to go forward with Friday? One of us can lead it.

On Thu, Jul 7, 2016 at 11:59 AM, Michael Hulet <notifications@github.com>
wrote:

> According to the poll in the Slack, it looks like Friday is a solid
> recurring day to do it, as that's the number winning out last time I
> checked. That being said, I'll have to be rather late to this Friday's
> (7/15, as it turns out), because that's my grandfather's birthday, and I'll
> be out to dinner with him for the first part of it
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/589#issuecomment-231174677>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-BGwUvEQ1yB1T9yMEYihSqZr8BPQks5qTUyAgaJpZM4JDw-M>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by raysarebest** [comment]
That seems to be when the most people are free, so I think that's the best time to have it

**Comment by zachlatta** [comment]
Gotcha, I'll leave it to Max or Selynna to coordinate who'll lead it from
here. Let's make sure you can make it on time for the next one, you're such
an important part of this community :-).

On Thu, Jul 7, 2016 at 12:05 PM, Michael Hulet <notifications@github.com>
wrote:

> That seems to be when the most people are free, so I think that's the best
> time to have it
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/589#issuecomment-231176233>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-Ew5nJPhdE9FBZAW_LicmDi9AM_Fks5qTU3jgaJpZM4JDw-M>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
I'm going to go ahead and close this. We're having hack night this Friday (7/15).
