### ISSUE TITLE
Choose a theme for Hack Night

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#590]
This can be closed once we've decided on a theme and someone puts it in a comment on this issue.

**Comment by MaxWofford** [comment]
On second thought, let's record the theme in the #hack-night-organizers channel on slack. That way the theme will be a surprise.

**Comment by MaxWofford** [comment]
It's recorded in the channel.

**Comment by zachlatta** [comment]
Can you link to the specific message in the Slack channel where this is
recorded?

On Sat, Jul 9, 2016 at 1:15 PM, Max Wofford <notifications@github.com>
wrote:

> It's recorded in the channel.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/590#issuecomment-231553610>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-PgFsAt5ZsdSUb6nzGZVPbWyAQryks5qUAFIgaJpZM4JDw-5>
> .
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by raysarebest** [comment]
[Here](https://starthackclub.slack.com/archives/hack-night-organizers/p1467649946000065)'s the original proposition by Markus Torpel, which all in the channel reacted to with ☀️ in support, and [here](https://starthackclub.slack.com/archives/hack-night-organizers/p1467961161000079)'s later on when @JSneak responded that Summer was the consensus when asked about it
