### ISSUE TITLE
Write up a checklist/schedule of events at Hack Night

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#591]

**Comment by metmets** [comment]
Quick schedule:
 5:00~5:20 Gathering people/ chatting/explaining stuff.
 5:20 LET THE HACKING GAMES BEGIN
 9:35 Last 5 or so minutes
 9:40/:45 Begin demos
 10:00 The end!

Of course the more people come the more time is needed for demos

**Comment by MaxWofford** [comment]
Thanks @metmets!
