### ISSUE TITLE
Testing again

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#599]
Sorry, please ignore this as well.

**Comment by MaxWofford** [comment]
@zachlatta Would it make sense to do this with a test repo outside of Hack Club?

**Comment by zachlatta** [comment]
Unfortunately had to test this with a repo inside of the Hack Club org :-/.

Sorry for the extra pings.

On Thu, Jul 14, 2016 at 2:14 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Would it make sense to do this
> with a test repo outside of Hack Club?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/meta/issues/599#issuecomment-232794491>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-CroK0rc1ckhE8enw1BWK7bJBbp8ks5qVqa-gaJpZM4JLoFW>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
