### ISSUE TITLE
Create blocking label for this repo

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#601]
So we can mark when issues are blocking on other stuff.

**Comment by zachlatta** [comment]
Make sure to apply this to #584.

**Comment by MaxWofford** [comment]
Added! 
![screenshot_2016-07-13_13 28 55](https://cloud.githubusercontent.com/assets/5891442/16818661/c5da5c70-48fd-11e6-80c0-d9be47e2c923.png)
