### ISSUE TITLE
Get cups and label maker 

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#605]
- [x] Label maker (note: Sanil will be bringing it)
- [x] Cups

**Comment by MaxWofford** [comment]
I've got a label maker in my bag you can borrow.

**Comment by ssun098** [comment]
No I mean like legit labels, not the labels we had for hack camp. Label
maker from CodeDay

**Comment by MaxWofford** [comment]
@ssun098 Would you please update this in ZenHub?

**Comment by ssun098** [comment]
done
