### ISSUE TITLE
Send out follow-up email

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#613]
We're going to send two follow-ups to the attendees:

_Immediately after the event:_

- Link to how to set up your .tech domain with your GitHub Pages site
- Link to our other workshops
- Link to DM the sender of the email on Slack

_3 days after the event:_

- A check-in to see if we can help with anything
- Link to DM the sender of the email on Slack

**Comment by MaxWofford** [comment]
This email should include instructions on how to get a free .tech domain (see https://github.com/hackclub/meta/issues/611#issuecomment-233165546).

**Comment by zachlatta** [comment]
Blocking on #610.

**Comment by MaxWofford** [comment]
@zachlatta Ping on this.

**Comment by zachlatta** [comment]
Done! Email is queued to send at 8AM tomorrow.
