### ISSUE TITLE
Kick-off email for existing clubs

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#633]
From https://docs.google.com/spreadsheets/d/1H3eWAH3trXgGudJgl_-bVHUe7jLgoJnQuBscMgirDGA/edit#gid=0

1. Yay you're in/ school year
2. Here's the shit you need to know

**Comment by ssun098** [comment]
Done

**Comment by MaxWofford** [comment]
![](https://media.giphy.com/media/3o7abrRFnymlummn60/giphy.gif)
