### ISSUE TITLE
Get presence at every SF hackathon

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#635]
From https://docs.google.com/spreadsheets/d/1H3eWAH3trXgGudJgl_-bVHUe7jLgoJnQuBscMgirDGA/edit#gid=0

**Comment by MaxWofford** [comment]
@kyleemile: You noted that this is on-hold in the spreadsheet. Should we track this issue?

**Comment by kyleemile** [comment]
Yeah, I say track it.

**Comment by SyncyMcSyncface** [comment]
Yeah, lets track it.

[--- Commented from Asana.com
#commenter Kyle Emile
---[aa]

**Comment by zachlatta** [comment]
No longer using GitHub to track this. Closing.
