### ISSUE TITLE
Story telling

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#636]
This issue is copied over from https://docs.google.com/spreadsheets/d/1H3eWAH3trXgGudJgl_-bVHUe7jLgoJnQuBscMgirDGA/edit#gid=0

@kyleemile I'm not totally clear what this entails. Could you comment with the success condition, or "what needs to happen for this issue to be closed"?

**Comment by kyleemile** [comment]
I will be keeping this top of mind.
