### ISSUE TITLE
Send acceptance/rejection email for last week interviews

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#643]

**Comment by MaxWofford** [comment]
Completed my portion of the task. There are still a few more candidates that need decision emails sent out. Handing off to you, https://app.asana.com/0/169784042795144/169784042795144.

[--- Commented from Asana.com
#commenter Zach Latta
---[aa]

**Comment by SyncyMcSyncface** [comment]
Done.

[--- Commented from Asana.com
#commenter Kyle Emile
---[aa]
