### ISSUE TITLE
Get remaining media release forms from students we shot with on 08.24.16

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/meta#648]
This issue is to get the remaining media release forms from students that we shot footage with on Wednesday, 08.24.16.

This can be closed when the media release forms have been added to the shared Dropbox folder with the other releases.

If you're interested in this task and don't know about or have access to the folder in question, just let me know and I'll share it.

**Comment by ssun098** [comment]
Done!

**Comment by MaxWofford** [comment]
The versions you uploaded are super low quality and not very legible. Can you replace with better quality uploads?

[--- Commented from Asana.com
#commenter Zach Latta
---[aa]

**Comment by MaxWofford** [comment]
Should be fixed now

[--- Commented from Asana.com
#commenter Selynna Sun
---[aa]
