### ISSUE TITLE
Order t-shirts for Fast Forward

### ISSUE THREAD

**Issue by ssun098** [hackclub/meta#655]
We need tshirts for Fast Forward - this entails contacting vendors and securing a deal.
This issue can be closed once we physically have the tshirts.

**Comment by zachlatta** [comment]
I got introduced to Teespring's direct order people and it sounds like they'll give us their lowest rate. I'll CC you on the thread, @ssun098.

**Comment by zachlatta** [comment]
Shirts have been ordered!
