### ISSUE TITLE
Make sure all clubs in Club Management pipeline are in correct stage. 

### ISSUE THREAD

**Issue by kyleemile** [hackclub/meta#657]
This issue can be closed once there are no clubs in the unknown stage in Club Management Streak pipeline.

**Comment by zachlatta** [comment]
Closing this issue because it's unclear what specifically needs to happen for it to be closed.

**Comment by zachlatta** [comment]
Closing this issue because I believe the context of it is larger than currently described.

I believe this issue also entails getting all of our clubs into our call process. Correct me if wrong.
