### ISSUE TITLE
Update organization logos on all the things

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#658]
As part of the redesign of https://hackclub.com, we changed the color of our logo and removed the gradient in #653.

This issue entails updating our logo on the various Hack Club accounts online. It can be closed once our logo on the following sites has been updated:

- [x] Facebook
- [x] Twitter
- [x] GitHub
- [x] Slack

~~- [ ] Medium~~

Comment if I missed any sites that it should be updated on.

**Comment by ssun098** [comment]
Done!

**Comment by ssun098** [comment]
Didn't update Medium because there isn't any logo/Hack Club graphics visible
