### ISSUE TITLE
Update Twitter colors to match new logo color

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#660]
If you check out our Twitter page (see below), the "Tweet to" and "Message" buttons don't match our logo's color. Same deal with the numbers under "following", "followers", and "likes".

Can you update the colors specified on our profile to match the logo?

<img width="858" alt="screen shot 2016-09-06 at 8 04 03 am" src="https://cloud.githubusercontent.com/assets/992248/18278900/9649b858-7408-11e6-954f-7a04ec97879e.png">

**Comment by ssun098** [comment]
Updated!
