### ISSUE TITLE
Gather club leader testimonials

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#661]
This issue is to track gathering the testimonials that'll be added to the website in hackclub/website#264.

@ssun098: can you get 3-5 testimonials from club leaders that talk about how awesome Hack Club is?

Here are the sorts of things I want mentioned in the testimonials:

- Hack Club made it super easy to start a great coding club
- By starting a Hack Club, they were able to build community they always wished existed at their school
- They started being the only coder at their school and now their are tons of hackers, thanks to Hack Club
- They started a club and it's been way better than they expected

I'll also want you to get headshots of each person that gives a testimonial. For the testimonials we select, we'll put them on the website with the club leader's name, headshot, school name, and link to their Hack Club's website, if their club has one.

Testimonials should be 1-2 sentences. Really short and to the point.

This issue can be closed once you've commented on this issue with the testimonials, names of the people that gave them, and headshots for each person.

**Comment by ssun098** [comment]
https://docs.google.com/spreadsheets/d/1LUawi_CPGcWVHlWQQHydvctcWWLwZhak3-Ar1XSbEkU/edit#gid=0 All the testimonials will be in here. I have 4/5 rn, and I'm still waiting on a headshot from 2

**Comment by ssun098** [comment]
This can be closed once there are 2-3 female co-leads giving testimonials as well

**Comment by ssun098** [comment]
Done!
