### ISSUE TITLE
Update favicons to new logo

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#662]
This is kind of an extension to #658, but since the deliverable is different, I decided to create a separate issue.

As part of changing our logo in #653, it's important for us to update the favicons we're using across sites to the new logo.

To start, we should update the favicon on https://hackclub.com and https://workshops.hackclub.com. Here's how to do it:

1. Create an ICO version of the new logo (the version with just the h on the red background) and submit a pull request to add it to the `hackclub/meta:logos/` directory. Call the file `favicon.ico`.
2. Submit pull requests to update `hackclub/website:app/assets/images/favicon.ico` and `hackclub/lecture-hall:app/assets/images/favicon.ico` to the `favicon.ico` file you created in the previous step.

Let me know if you have questions!

**Comment by ssun098** [comment]
https://github.com/hackclub/website/pull/267 fixes hackclub/website

**Comment by ssun098** [comment]
https://github.com/hackclub/lecture-hall/pull/48 fixes hackclub/lecture-hall

**Comment by zachlatta** [comment]
Both favicons you submitted are 7.7MB, which is over 900 times as large as the previous favicons.

Can you update the PRs with much smaller favicons? The current one's 8KB.

**Comment by ssun098** [comment]
Updated, is it better now?

**Comment by zachlatta** [comment]
Yup! Merged both.
