### ISSUE TITLE
Order business cards for Selynna, Matthew, and Victor

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#666]
In #665 we ordered business cards for myself and @kyleemile for the Fast Forward events happening this week.

This issue entails using the same business card template from #665 and ordering 100 business cards each for @ssun098, @MatthewKwong, and @LabLayers.

The business cards we ordered for #665 had a variety of illustrations on their backs to make the cards a bit more fun to hand out, we're going to stick with a single illustration on the back for each 100 card set this time around (you can use the same illustration on the back for everyone or use a different one for each person).

Reach out to @LabLayers to get the designs for each person.

Each business card should have the individual's email, title, and phone number. Reach out to @kyleemile to get the info for each person.

This issue can be closed once the order has been placed. No need to wait to have the cards in our hand to close the issue.

**Comment by ssun098** [comment]
Ordered!
