### ISSUE TITLE
Create marketing materials for CPS

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#678]
@MaxWofford and I need to meet offline to figure out the deliverable for this.

/cc @kyleemile

**Comment by zachlatta** [comment]
Alright, we met offline and _the deliverable has been set_.

We'll be making three posters, to be posted one week at a time, in order, inside of the CPS math and science classrooms.

PDF of mockup:

[2017-02-27_cps_poster_idea.pdf](https://github.com/hackclub/meta/files/805203/2017-02-27_cps_poster_idea.pdf)

- First poster
  - ROT13 encoded text (hardest difficulty level)
  - Include general overview of Hack Club and mention that we want to get a club started at their high school. Will include a special code to use when applying.
    - Make sure that it's clear where to actually put the code. Right now the application form doesn't have a clear place for referral codes. Perhaps we can tell them to put it into the "how did you hear about Hack Club" field?
- Second poster
  - Will be posted to the right of the first poster one week later
  - Will be binary encoded and include photos of clubs / club members / club projects (will leave to your discretion)
  - Will have a separate code to use when applying
- Third poster
  - Generic non-encoded Hack Club poster
    - This poster should be able to stand alone and be used at other schools without referring to the first or second poster (this'll let us separately send this to teachers for the Matthew campaign)
  - Will have another separate code to use when applying

We'll send these to Rukiya when they're done and have her tell teachers to post each one, in order, next to the previous one. One new poster each week.

**Comment by MaxWofford** [comment]
Here's the general layout so far (ignore most of the copy):

![](http://i.imgur.com/MCYvQ5S.png)

**Comment by MaxWofford** [comment]
@hackclub/staff I'd love your opinion on this copy for the first poster:

```
Welcome to the club,

We’re a non-profit that helps high schoolers start their own coding clubs.
We’ve got curriculum, an online community, and a bunch of swag you’ll have free
access to. Looking forward to your application :-).

And don’t worry if you can’t code just yet – the important part is that you’re
willing to learn to build projects with code. That’s the real focus here:
having the power to learn to build things you want to see in the world.

More posters will come soon... stay tuned! You may want to check out
https://blog.hackclub.com though, it might not be the same by the time the last
poster shows up.

Looking forward to your application,

Max (@msw)
```

**Comment by MaxWofford** [comment]
Also, I'd love your feedback on [this](https://www.notion.so/CPS-Poster-Content-508c5a137c8c4b639d8b2f70b8d18b94#2e87888381fc4d4dbb46000290efccab). It's the copy of the last (non-encoded poster).

**Comment by zachlatta** [comment]
Thoughts on this? A little more ominous:

```

Welcome to the club,

We're Hack Club, the worldwide movement of student-led coding clubs. We're
about turning fellow students into hackers -- people who build things that,
often unintuitively, change the world. We are the future's Alan Kays, Ken
Thompsons, and Grace Hoppers.

We're here because we want El Segundo High School to be the next place we
infiltrate. Don't worry if you can't code just yet -- the important part is
that you're willing to learn and share the knowledge with your peers.

More posters will show up soon -- keep the fact that you were able to decrypt
this on the dl. Do check out https://blog.hackclub.com, it may not be the same
by the time the next poster shows up.

- msw
```

**Comment by zachlatta** [comment]
Need a better phrase than `keep this on the dl`.

**Comment by MaxWofford** [comment]
Note to self: @paked had the idea to have a bar/qr code to a paste bin of all this text so people don't have  to type it in manually.

**Comment by MaxWofford** [comment]
![](https://media.giphy.com/media/3orieTbyzN9QNCDANa/giphy.gif)

https://imgur.com/a/3qUpa

![](http://i.imgur.com/LFt1Bov.png)

![](http://i.imgur.com/lOhogsL.png)

![](http://i.imgur.com/EoBkBPR.png)

**Comment by MaxWofford** [comment]
I've drafted an email to send this off, just waiting for @kyleemile's review of it.

**Comment by MaxWofford** [comment]
Just sent out the email. Thanks for the edit @kyleemile. ![](https://media.giphy.com/media/l4HnKwxpPDoPmL9bG/giphy.gif)
