### ISSUE TITLE
Source people that participated at CodeDay from GitHub

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#679]
I'll leave a comment in a few minutes with what specifically needs to happen for this task to be done.

**Comment by zachlatta** [comment]
General outline for how I might go about accomplishing this:

1. Search for people that made GitHub repos with a name or description that includes the word "CodeDay" in the past few weeks
2. For every person, you can get their contact info by running their GitHub username through the `info_from_github_username` function in https://github.com/hackclub/high-schooler-recruiting (see https://github.com/hackclub/high-schooler-recruiting/blob/master/bin/github.rb#L181-L198)
  - This'll scrape their profile and get their name and email from their git commit history
  - For the people that have GitHub info protection on (where you use a noreply email @github.com for your commits), you'll have to figure out their info manually
3. Create a box for each person you find in the Lead stage of the "2017-01-23 Direct Sourcing" pipeline (the key of the pipeline is `agxzfm1haWxmb29nYWVyNAsSDE9yZ2FuaXphdGlvbiINemFjaGxhdHRhLmNvbQwLEghXb3JrZmxvdxiAgIDA0IuXCgw`).
  - I'd create a new option for the Type field called "CodeDay"

**Comment by MaxWofford** [comment]
Closing this because @paked completed this in a later week.
