### ISSUE TITLE
Email all sourced leads from CodeDay about starting a Hack Club

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#680]
This is blocking on #679.

Reach out to @paked and myself to discuss copy for this email.

I'll comment with the specific Streak flow that needs to happen to accomplish this task.

**Comment by zachlatta** [comment]
1. Go to the "Assigned to Me" view of the "2017-01-23 Direct Sourcing" pipeline. This'll only show the boxes that are assigned to you.
2. For each box that's assigned to you, do the obvious and email them about starting a Hack Club
    - See the boxes in "Won - Received Application" for people that @paked and I emailed for example copy

**Comment by zachlatta** [comment]
There's also a "My Follow-Ups" view that'll show you a list of everyone that you're due to follow-up with.

**Comment by MaxWofford** [comment]
Closing this because it is no longer relevant. @paked finished this task in a later week.
