### ISSUE TITLE
Set up Jabber server

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#69]

**Comment by jonleung** [comment]
@zachlatta is this still relevant?

**Comment by zachlatta** [comment]
Yup! Just far in the backlog.

I would like to eventually have a Jabber server members of the team could
use set up though.

On Tue, Aug 18, 2015 at 11:46 AM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> is this still relevant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/69#issuecomment-132315310>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
Since we're using Slack now, this no longer seems necessary. Closing this for the sake of biasing for closing issues. @zachlatta feel free to reopen.
