### ISSUE TITLE
Clarify the wording we should use for onboarding calls

### ISSUE THREAD

**Issue by zachlatta** [hackclub/meta#83]
We want to make joining hackEDU feel "exclusive" and introduce scarcity when talking with people.

**Comment by jonleung** [comment]
:+1: 

I also love how this is public lol

**Comment by willium** [comment]
:+1:

**Comment by jonleung** [comment]
@zachlatta it seems like you've made progress on this task or at least figuring out how you want to do it. Is this being tracked in another issue somewhere? Shall we move this task to `Backlog?
